"use client";

import { createContext, useContext, useEffect, useState } from "react";

export type Lang = "is" | "en";

type Dict = Record<string, { is: string; en: string }>;

// App-shell chrome strings. Per-screen content can adopt useLang() incrementally.
export const DICT: Dict = {
  "grp:Dagleg vinna": { is: "Dagleg vinna", en: "Daily work" },
  "grp:Laun & fólk": { is: "Laun & fólk", en: "Pay & people" },
  "grp:Greining": { is: "Greining", en: "Analytics" },
  "grp:Starfsmaður": { is: "Starfsmaður", en: "Employee" },
  "nav:dashboard": { is: "Mælaborð", en: "Dashboard" },
  "nav:schedule": { is: "Vaktaplan", en: "Schedule" },
  "nav:attendance": { is: "Tímaskráning", en: "Time tracking" },
  "nav:payroll": { is: "Launakeyrslur", en: "Payroll" },
  "nav:employees": { is: "Starfsfólk", en: "Employees" },
  "nav:reports": { is: "Skýrslur", en: "Reports" },
  "nav:performance": { is: "Frammistaða", en: "Performance" },
  "nav:employeeapp": { is: "Starfsmannaapp", en: "Employee app" },
  "nav:chat": { is: "Spjall", en: "Chat" },
  "nav:settings": { is: "Stillingar", en: "Settings" },
  "nav:help": { is: "Hjálp", en: "Help" },
  search: { is: "Leita…", en: "Search…" },
  create: { is: "Búa til", en: "Create" },
  "create:shift": { is: "Ný vakt", en: "New shift" },
  "create:emp": { is: "Nýr starfsmaður", en: "New employee" },
  "create:plan": { is: "Nýtt vaktaplan", en: "New schedule" },
  "create:loc": { is: "Nýr staður", en: "New location" },
  notifications: { is: "Tilkynningar", en: "Notifications" },
  seeall: { is: "Sjá allar →", en: "See all →" },
  "acct:role": { is: "Skipta um aðgang / hlutverk", en: "Switch role / access" },
  "acct:loc": { is: "Velja fyrirtæki / stað", en: "Choose company / location" },
  "acct:kiosk": { is: "Stimpilklukka (kiosk)", en: "Time clock (kiosk)" },
  "acct:settings": { is: "Stillingar", en: "Settings" },
  "acct:help": { is: "Hjálp", en: "Help" },
  "acct:dark": { is: "Dökkt útlit", en: "Dark mode" },
  "Ljóst útlit": { is: "Ljóst útlit", en: "Light mode" },
  "Dökkt útlit virkt": { is: "Dökkt útlit virkt", en: "Dark mode on" },
  "Ljóst útlit virkt": { is: "Ljóst útlit virkt", en: "Light mode on" },
  "Velkomin í VAKTO": { is: "Velkomin í VAKTO", en: "Welcome to VAKTO" },
  "Engin tímaskráning enn": { is: "Engin tímaskráning enn", en: "No time records yet" },
  "Tímaskráning birtist hér um leið og starfsfólk byrjar að stimpla inn — gegnum appið eða Kiosk-skjáinn. Bættu fyrst við starfsfólki.": { is: "Tímaskráning birtist hér um leið og starfsfólk byrjar að stimpla inn — gegnum appið eða Kiosk-skjáinn. Bættu fyrst við starfsfólki.", en: "Time records appear here as soon as staff start clocking in — via the app or the Kiosk screen. Add staff first." },
  "Engar skýrslur enn": { is: "Engar skýrslur enn", en: "No reports yet" },
  "Skýrslur byggja á vöktum, tímaskráningu og launakeyrslum. Bættu við starfsfólki og birtu vaktaplan — þá fyllast greiningarnar sjálfkrafa.": { is: "Skýrslur byggja á vöktum, tímaskráningu og launakeyrslum. Bættu við starfsfólki og birtu vaktaplan — þá fyllast greiningarnar sjálfkrafa.", en: "Reports build on shifts, time records and payroll. Add staff and publish a schedule — the analytics fill in automatically." },
  "Engin frammistöðugögn enn": { is: "Engin frammistöðugögn enn", en: "No performance data yet" },
  "Þróun, framlegð og laun% birtast hér þegar þú ert komin/n með veltu og launakeyrslur. Byrjaðu á að bæta við starfsfólki og skrá veltu.": { is: "Þróun, framlegð og laun% birtast hér þegar þú ert komin/n með veltu og launakeyrslur. Byrjaðu á að bæta við starfsfólki og skrá veltu.", en: "Trends, margin and labor % appear here once you have revenue and payroll. Start by adding staff and recording revenue." },
  "Engar launakeyrslur enn": { is: "Engar launakeyrslur enn", en: "No payroll runs yet" },
  "Bættu fyrst við starfsfólki með taxta og kjarasamningi. Þá getur þú keyrt launakeyrslu sem VAKTO reiknar sjálfkrafa og Payday sér um skil.": { is: "Bættu fyrst við starfsfólki með taxta og kjarasamningi. Þá getur þú keyrt launakeyrslu sem VAKTO reiknar sjálfkrafa og Payday sér um skil.", en: "First add staff with pay rate and union agreement. Then you can run payroll — VAKTO computes it automatically and Payday handles filing." },
  "af 4 skrefum kláruð — settu kerfið upp á nokkrum mínútum.": { is: "af 4 skrefum kláruð — settu kerfið upp á nokkrum mínútum.", en: "of 4 steps done — set the system up in a few minutes." },
  "Skrá veltu / tengja Inventra": { is: "Skrá veltu / tengja Inventra", en: "Record revenue / connect Inventra" },
  "Þegar þú hefur bætt við starfsfólki og birt vaktaplan birtast hér lifandi tölur — laun af tekjum, launakostnaður, frávik og yfirvinna.": { is: "Þegar þú hefur bætt við starfsfólki og birt vaktaplan birtast hér lifandi tölur — laun af tekjum, launakostnaður, frávik og yfirvinna.", en: "Once you add staff and publish a schedule, live numbers appear here — labor % of revenue, labor cost, variance and overtime." },
  "acct:logout": { is: "Útskrá", en: "Sign out" },
  "role:owner": { is: "Stjórnandi", en: "Owner" },
  "role:manager": { is: "Vaktstjóri", en: "Manager" },
  "role:employee": { is: "Starfsmaður", en: "Employee" },
  "role:contractor": { is: "Verktaki", en: "Contractor" },
  "chat:title": { is: "Aðstoð VAKTO", en: "VAKTO support" },
  "chat:sub": { is: "Við svörum venjulega innan fárra mínútna", en: "We usually reply within a few minutes" },
  "chat:hi": { is: "Hæ! Hvernig getum við aðstoðað þig í dag?", en: "Hi! How can we help you today?" },
  "chat:hint": { is: "Þú getur spurt um vaktaplan, launakeyrslu, kjarasamninga eða tengingar.", en: "Ask about scheduling, payroll, union agreements or integrations." },
  "chat:ph": { is: "Skrifaðu skilaboð…", en: "Type a message…" },
  "cookie:h": { is: "Við notum vafrakökur", en: "We use cookies" },
  "cookie:p": { is: "Til að bæta upplifun, greina notkun og birta viðeigandi efni.", en: "To improve your experience, analyse usage and show relevant content." },
  "cookie:more": { is: "Nánar um vafrakökur", en: "About cookies" },
  "cookie:allow": { is: "Leyfa allar", en: "Allow all" },
  "cookie:deny": { is: "Hafna öllum", en: "Reject all" },
  "cookie:settings": { is: "Stillingar á vafrakökum", en: "Cookie settings" },

  // page-header titles (keyed by the Icelandic string)
  "Mælaborð": { is: "Mælaborð", en: "Dashboard" },
  "Vaktaplan": { is: "Vaktaplan", en: "Schedule" },
  "Tímaskráning": { is: "Tímaskráning", en: "Time tracking" },
  "Launakeyrslur": { is: "Launakeyrslur", en: "Payroll" },
  "Starfsfólk": { is: "Starfsfólk", en: "Employees" },
  "Skýrslur": { is: "Skýrslur", en: "Reports" },
  "Frammistaða": { is: "Frammistaða", en: "Performance" },
  "Mitt svæði": { is: "Mitt svæði", en: "My area" },
  "Spjall": { is: "Spjall", en: "Chat" },
  "Stillingar": { is: "Stillingar", en: "Settings" },
  // page-header subtitles
  "Þriðjudagur 23. júní 2026": { is: "Þriðjudagur 23. júní 2026", en: "Tuesday 23 June 2026" },
  "Vika 22.–28. júní 2026": { is: "Vika 22.–28. júní 2026", en: "Week 22–28 June 2026" },
  "Áætlað vs raun · þessi vika": { is: "Áætlað vs raun · þessi vika", en: "Planned vs actual · this week" },
  "Launagreiðslur · 2026": { is: "Launagreiðslur · 2026", en: "Payroll runs · 2026" },
  "Greiningar og frammistaða": { is: "Greiningar og frammistaða", en: "Analytics and performance" },
  "Þróun, framlegð og launasundurliðun": { is: "Þróun, framlegð og launasundurliðun", en: "Trends, margin and pay breakdown" },
  "Vaktir, laun, réttindi og prófíll": { is: "Vaktir, laun, réttindi og prófíll", en: "Shifts, pay, rights and profile" },
  "Skilaboð til starfsfólks og stjórnenda": { is: "Skilaboð til starfsfólks og stjórnenda", en: "Messages to staff and managers" },
  "Reglur, kjarasamningar og tengingar": { is: "Reglur, kjarasamningar og tengingar", en: "Rules, union agreements and integrations" },

  // Starfsfólk screen
  "emp:new": { is: "+ Nýr starfsmaður", en: "+ New employee" },
  "emp:kpi:count": { is: "Starfsmenn", en: "Employees" },
  "emp:kpi:fte": { is: "Stöðugildi", en: "FTE" },
  "emp:kpi:over": { is: "Yfir starfshlutfalli", en: "Over employment ratio" },
  "emp:kpi:leave": { is: "Í fríi þessa viku", en: "On leave this week" },
  "emp:card": { is: "Starfsfólk", en: "Employees" },
  "emp:card:sub": { is: "launareikningur býr inni í hverjum starfsmanni — taxti, álög/kjarasamningur, frádráttur", en: "the pay profile lives inside each employee — rate, premiums/union agreement, deductions" },
  "emp:th:name": { is: "Nafn", en: "Name" },
  "emp:th:dept": { is: "Deild", en: "Department" },
  "emp:th:type": { is: "Tegund", en: "Type" },
  "emp:th:rate": { is: "Taxti", en: "Rate" },
  "emp:th:ratio": { is: "Starfshlutf.", en: "Ratio" },
  "emp:th:union": { is: "Kjarasamningur", en: "Union agreement" },
  "emp:th:status": { is: "Staða", en: "Status" },
  "emp:hourly": { is: "Tímakaup", en: "Hourly" },
  "emp:monthly": { is: "Mánaðarlaun", en: "Monthly" },
  "emp:active": { is: "Virk", en: "Active" },
  "emp:overtime": { is: "Yfirvinna", en: "Overtime" },
  "emp:overratio": { is: "Yfir hlutfalli", en: "Over ratio" },
  "emp:subtitle": { is: "starfsmenn", en: "employees" },
  "emp:fteword": { is: "stöðugildi", en: "FTE" },
  "emp:footer": { is: "Smelltu á starfsmann til að stilla taxta, álög og kjarasamning — eða velja tilbúinn samning sem fyllir reglurnar.", en: "Click an employee to set rate, premiums and union agreement — or pick a ready agreement that fills the rules." },
  "emp:demo": { is: " · (demo-gögn — tengdu Supabase til að sjá rauntölur)", en: " · (demo data — connect Supabase for live figures)" },
  "emp:shows": { is: "Sýnir", en: "Showing" },

  // shared words
  "klst": { is: "klst", en: "hrs" },
  "stig": { is: "stig", en: "pts" },
  "Vika": { is: "Vika", en: "Week" },
  "Dagur": { is: "Dagur", en: "Day" },
  "Mánuður": { is: "Mánuður", en: "Month" },
  "Ár": { is: "Ár", en: "Year" },
  "Ársfj.": { is: "Ársfj.", en: "Quarter" },
  "Tímar": { is: "Tímar", en: "Hours" },
  "Yfirvinna": { is: "Yfirvinna", en: "Overtime" },
  "vs maí": { is: "vs maí", en: "vs May" },
  "vs í gær": { is: "vs í gær", en: "vs yesterday" },
  "vs fyrri viku": { is: "vs fyrri viku", en: "vs last week" },
  "Allar deildir": { is: "Allar deildir", en: "All departments" },
  "Allir staðir": { is: "Allir staðir", en: "All locations" },
  "Leita að starfsmanni": { is: "Leita að starfsmanni", en: "Search employee" },

  // Dashboard
  "Sérsníða": { is: "Sérsníða", en: "Customise" },
  "Komdu þér af stað með VAKTO": { is: "Komdu þér af stað með VAKTO", en: "Get started with VAKTO" },
  "3 af 5 skref kláruð — settu kerfið upp á nokkrum mínútum.": { is: "3 af 5 skref kláruð — settu kerfið upp á nokkrum mínútum.", en: "3 of 5 steps done — set up the system in a few minutes." },
  "Fela": { is: "Fela", en: "Hide" },
  "Fyrirtæki & staðir": { is: "Fyrirtæki & staðir", en: "Company & locations" },
  "Bæta við starfsfólki": { is: "Bæta við starfsfólki", en: "Add staff" },
  "Setja launataxta": { is: "Setja launataxta", en: "Set pay rates" },
  "Gera fyrsta vaktaplan": { is: "Gera fyrsta vaktaplan", en: "Create first schedule" },
  "Tengja launakerfi": { is: "Tengja launakerfi", en: "Connect payroll" },
  "Í gær · 24. júní 2026": { is: "Í gær · 24. júní 2026", en: "Yesterday · 24 June 2026" },
  "Tímar og laun gærdagsins eru komin inn — dagurinn í dag uppfærist í rauntíma.": { is: "Tímar og laun gærdagsins eru komin inn — dagurinn í dag uppfærist í rauntíma.", en: "Yesterday's hours and pay are in — today updates in real time." },
  "Áætlaðir tímar": { is: "Áætlaðir tímar", en: "Planned hours" },
  "Raun tímar": { is: "Raun tímar", en: "Actual hours" },
  "Frávik": { is: "Frávik", en: "Variance" },
  "Launakostnaður gærdagsins": { is: "Launakostnaður gærdagsins", en: "Yesterday's labor cost" },
  "Laun% 32,4% · 47 vaktir · 8,2% yfirvinna": { is: "Laun% 32,4% · 47 vaktir · 8,2% yfirvinna", en: "Labor% 32,4% · 47 shifts · 8,2% overtime" },
  "Laun af tekjum": { is: "Laun af tekjum", en: "Labor of revenue" },
  "Launakostnaður (vika)": { is: "Launakostnaður (vika)", en: "Labor cost (week)" },
  "Unnir tímar (vika)": { is: "Unnir tímar (vika)", en: "Hours worked (week)" },
  "/ 368 áætl": { is: "/ 368 áætl", en: "/ 368 plan" },
  "yfir plani": { is: "yfir plani", en: "over plan" },
  "Yfirvinna (vika)": { is: "Yfirvinna (vika)", en: "Overtime (week)" },
  "Launakostnaður — samanburður": { is: "Launakostnaður — samanburður", en: "Labor cost — comparison" },
  "þetta tímabil vs fyrra": { is: "þetta tímabil vs fyrra", en: "this period vs previous" },
  "Þetta tímabil": { is: "Þetta tímabil", en: "This period" },
  "Fyrra tímabil": { is: "Fyrra tímabil", en: "Previous period" },
  "Breyting": { is: "Breyting", en: "Change" },
  "Vinnum við eftir plani?": { is: "Vinnum við eftir plani?", en: "Are we on plan?" },
  "raun tímar vs áætlun · þessi vika": { is: "raun tímar vs áætlun · þessi vika", en: "actual hours vs plan · this week" },
  "94% eftir plani": { is: "94% eftir plani", en: "94% on plan" },
  "Þarf athygli": { is: "Þarf athygli", en: "Needs attention" },
  "3 atriði": { is: "3 atriði", en: "3 items" },
  "Yfirvinnu-áhætta: Ómar": { is: "Yfirvinnu-áhætta: Ómar", en: "Overtime risk: Ómar" },
  "18 klst yfir starfshlutfalli í mánuðinum": { is: "18 klst yfir starfshlutfalli í mánuðinum", en: "18 hrs over employment ratio this month" },
  "Hvíldartími: Jón": { is: "Hvíldartími: Jón", en: "Rest time: Jón" },
  "9 klst milli vakta — undir 11 klst lágmarki": { is: "9 klst milli vakta — undir 11 klst lágmarki", en: "9 hrs between shifts — under the 11 hr minimum" },
  "laga": { is: "laga", en: "fix" },
  "Vantar útstimplun: Mína": { is: "Vantar útstimplun: Mína", en: "Missing clock-out: Mína" },
  "stimplaði inn 08:02, engin útstimplun í gær": { is: "stimplaði inn 08:02, engin útstimplun í gær", en: "clocked in 08:02, no clock-out yesterday" },
  "skoða": { is: "skoða", en: "review" },
  "Mánuðurinn · júní 2026": { is: "Mánuðurinn · júní 2026", en: "The month · June 2026" },
  "· borið saman við maí": { is: "· borið saman við maí", en: "· compared to May" },
  "Unnir tímar": { is: "Unnir tímar", en: "Hours worked" },
  "Launakostn. (byrði)": { is: "Launakostn. (byrði)", en: "Labor cost (burden)" },
  "Laun% (með byrði)": { is: "Laun% (með byrði)", en: "Labor% (with burden)" },
  "Launaspá (mánuður)": { is: "Launaspá (mánuður)", en: "Pay forecast (month)" },
  "brúttó · fyrir byrði": { is: "brúttó · fyrir byrði", en: "gross · before burden" },
  "batnar": { is: "batnar", en: "improving" },

  // Attendance
  "Sækja CSV": { is: "Sækja CSV", en: "Download CSV" },
  "Á vakt núna": { is: "Á vakt núna", en: "On shift now" },
  "Mætti of seint": { is: "Mætti of seint", en: "Late arrivals" },
  "Vantar útstimplun": { is: "Vantar útstimplun", en: "Missing clock-out" },
  "Frávik (klst)": { is: "Frávik (klst)", en: "Variance (hrs)" },
  "Fer yfir áætlun": { is: "Fer yfir áætlun", en: "Exceeding plan" },
  "stefnir í yfirvinnu eða aukinn kostnað": { is: "stefnir í yfirvinnu eða aukinn kostnað", en: "trending to overtime or higher cost" },
  "Áætlað vs raun í dag": { is: "Áætlað vs raun í dag", en: "Planned vs actual today" },
  "Áætlaður launakostnaður": { is: "Áætlaður launakostnaður", en: "Planned labor cost" },
  "Raun launakostnaður": { is: "Raun launakostnaður", en: "Actual labor cost" },
  "Raun laun% (klukknaðir tímar)": { is: "Raun laun% (klukknaðir tímar)", en: "Actual labor% (clocked hours)" },
  "Samþykkja": { is: "Samþykkja", en: "Approve" },
  "Tímaskráning vikunnar": { is: "Tímaskráning vikunnar", en: "Time records this week" },
  "smelltu á röð til að skoða og samþykkja": { is: "smelltu á röð til að skoða og samþykkja", en: "click a row to view and approve" },
  "Samþykkja allt": { is: "Samþykkja allt", en: "Approve all" },
  "3 bíða samþykkis": { is: "3 bíða samþykkis", en: "3 awaiting approval" },
  "th:Starfsm.": { is: "Starfsm.", en: "Employee" },
  "Áætluð vakt": { is: "Áætluð vakt", en: "Planned shift" },
  "Stimplað inn": { is: "Stimplað inn", en: "Clock in" },
  "Stimplað út": { is: "Stimplað út", en: "Clock out" },
  "Áætl.": { is: "Áætl.", en: "Plan" },
  "Raun": { is: "Raun", en: "Actual" },
  "Staða": { is: "Staða", en: "Status" },
  "Samþykki": { is: "Samþykki", en: "Approval" },

  // Payroll
  "↗ Flytja í Payday": { is: "↗ Flytja í Payday", en: "↗ Export to Payday" },
  "Launatímabil · 21. maí – 20. júní 2026": { is: "Launatímabil · 21. maí – 20. júní 2026", en: "Pay period · 21 May – 20 June 2026" },
  "Drög — bíður samþykkis": { is: "Drög — bíður samþykkis", en: "Draft — awaiting approval" },
  "Starfsmenn": { is: "Starfsmenn", en: "Employees" },
  "Brúttó": { is: "Brúttó", en: "Gross" },
  "Forskoða": { is: "Forskoða", en: "Preview" },
  "Keyra launakeyrslu": { is: "Keyra launakeyrslu", en: "Run payroll" },
  "Útborgað (júní)": { is: "Útborgað (júní)", en: "Net paid (June)" },
  "Heildarkostnaður": { is: "Heildarkostnaður", en: "Total cost" },
  "byrði": { is: "byrði", en: "burden" },
  "Staðgreiðsla": { is: "Staðgreiðsla", en: "Withholding" },
  "Tryggingagjald": { is: "Tryggingagjald", en: "Insurance levy" },
  "Útborgað": { is: "Útborgað", en: "Net paid" },
  "Lífeyrir": { is: "Lífeyrir", en: "Pension" },
  "Orlof": { is: "Orlof", en: "Holiday pay" },
  "Launakeyrsla — sundurliðun per starfsmann": { is: "Launakeyrsla — sundurliðun per starfsmann", en: "Payroll — breakdown per employee" },
  "21. maí – 20. júní 2026 · smelltu á starfsmann fyrir launaseðil": { is: "21. maí – 20. júní 2026 · smelltu á starfsmann fyrir launaseðil", en: "21 May – 20 June 2026 · click an employee for a payslip" },
  "Allir seðlar": { is: "Allir seðlar", en: "All payslips" },
  "Starfsmaður": { is: "Starfsmaður", en: "Employee" },
  "Lífeyrir+félag": { is: "Lífeyrir+félag", en: "Pension+union" },
  "Samtals · 12 starfsm.": { is: "Samtals · 12 starfsm.", en: "Total · 12 employees" },
  "Launakeyrslur — yfirlit": { is: "Launakeyrslur — yfirlit", en: "Payroll runs — overview" },
  "sundurliðun eftir mánuðum": { is: "sundurliðun eftir mánuðum", en: "breakdown by month" },
  "Byrði — júní 2026": { is: "Byrði — júní 2026", en: "Burden — June 2026" },
  "Brúttólaun": { is: "Brúttólaun", en: "Gross pay" },
  "Orlof 10,17%": { is: "Orlof 10,17%", en: "Holiday pay 10,17%" },
  "Mótframlag lífeyris 11,5%": { is: "Mótframlag lífeyris 11,5%", en: "Pension contribution 11,5%" },
  "Tryggingagjald 6,35%": { is: "Tryggingagjald 6,35%", en: "Insurance levy 6,35%" },
  "Útflutningur": { is: "Útflutningur", en: "Export" },
  "launakeyrsla & skil — tilbúið": { is: "launakeyrsla & skil — tilbúið", en: "payroll & filing — ready" },
  "sundurliðun per starfsmann": { is: "sundurliðun per starfsmann", en: "breakdown per employee" },
  "Flytja": { is: "Flytja", en: "Export" },
  "Sækja": { is: "Sækja", en: "Download" },
  "Vakto reiknar — Payday sér um skil, greiðslur og opinbera skýrslugerð.": { is: "Vakto reiknar — Payday sér um skil, greiðslur og opinbera skýrslugerð.", en: "Vakto calculates — Payday handles filing, payments and official reporting." },

  // Settings
  "Land & launareglur": { is: "Land & launareglur", en: "Country & pay rules" },
  "Ísland (virkt)": { is: "Ísland (virkt)", en: "Iceland (active)" },
  "staðgreiðsla, tryggingagjald, lífeyrir, orlof": { is: "staðgreiðsla, tryggingagjald, lífeyrir, orlof", en: "withholding, insurance levy, pension, holiday pay" },
  "virkt": { is: "virkt", en: "active" },
  "virk": { is: "virk", en: "active" },
  "Fleiri lönd": { is: "Fleiri lönd", en: "More countries" },
  "Noregur, Danmörk, Bretland": { is: "Noregur, Danmörk, Bretland", en: "Norway, Denmark, UK" },
  "væntanlegt": { is: "væntanlegt", en: "coming soon" },
  "Mótframlag lífeyris": { is: "Mótframlag lífeyris", en: "Pension contribution" },
  "Launatímabil": { is: "Launatímabil", en: "Pay period" },
  "Tengingar": { is: "Tengingar", en: "Integrations" },
  "launakeyrsla & skil": { is: "launakeyrsla & skil", en: "payroll & filing" },
  "tengt": { is: "tengt", en: "connected" },
  "velta í rauntíma — laun vs velta · smelltu til að sækja veltu": { is: "velta í rauntíma — laun vs velta · smelltu til að sækja veltu", en: "revenue in real time — labor vs revenue · click to fetch revenue" },
  "POS / sölukerfi": { is: "POS / sölukerfi", en: "POS / sales system" },
  "tengja": { is: "tengja", en: "connect" },
  "Staðir": { is: "Staðir", en: "Locations" },
  "+ Bæta við stað": { is: "+ Bæta við stað", en: "+ Add location" },
  "Hver staður hefur eigin starfsfólk, vaktaplan, laun% og tímabelti — fyrir keðjur og mörg útibú.": { is: "Hver staður hefur eigin starfsfólk, vaktaplan, laun% og tímabelti — fyrir keðjur og mörg útibú.", en: "Each location has its own staff, schedule, labor% and timezone — for chains and multiple branches." },
  "nýtt": { is: "nýtt", en: "new" },
  "Stöður (positions)": { is: "Stöður (positions)", en: "Positions" },
  "+ Ný staða": { is: "+ Ný staða", en: "+ New position" },
  "Notendur & aðgangur": { is: "Notendur & aðgangur", en: "Users & access" },
  "+ Bjóða notanda": { is: "+ Bjóða notanda", en: "+ Invite user" },
  "Eigandi — fullur aðgangur": { is: "Eigandi — fullur aðgangur", en: "Owner — full access" },
  "Eigandi": { is: "Eigandi", en: "Owner" },
  "Rekstrarstjóri — vaktir, laun, skýrslur": { is: "Rekstrarstjóri — vaktir, laun, skýrslur", en: "Operations manager — shifts, pay, reports" },
  "Stjórnandi": { is: "Stjórnandi", en: "Manager" },
  "eigin vaktir, tímar og laun": { is: "eigin vaktir, tímar og laun", en: "own shifts, hours and pay" },
  "Áskrift & greiðslur": { is: "Áskrift & greiðslur", en: "Subscription & billing" },
  "Vakto Business · mánaðarlega": { is: "Vakto Business · mánaðarlega", en: "Vakto Business · monthly" },
  "Fjöldi notenda": { is: "Fjöldi notenda", en: "Number of users" },
  "Verð á notanda": { is: "Verð á notanda", en: "Price per user" },
  "Samtals": { is: "Samtals", en: "Total" },
  "Næsta greiðsla": { is: "Næsta greiðsla", en: "Next payment" },
  "Greiðslumáti": { is: "Greiðslumáti", en: "Payment method" },
  "Uppfæra kort": { is: "Uppfæra kort", en: "Update card" },
  "Reikningar": { is: "Reikningar", en: "Invoices" },
  "Verð aðlagast sjálfkrafa þegar notendum fjölgar eða fækkar (per-notanda). Lítil teymi (≤5 starfsmenn) ókeypis.": { is: "Verð aðlagast sjálfkrafa þegar notendum fjölgar eða fækkar (per-notanda). Lítil teymi (≤5 starfsmenn) ókeypis.", en: "Pricing adjusts automatically as users are added or removed (per-user). Small teams (≤5 employees) free." },

  // Reports
  "Deild": { is: "Deild", en: "Department" },
  "Velta á starfsmann": { is: "Velta á starfsmann", en: "Revenue per employee" },
  "Velta á launatíma": { is: "Velta á launatíma", en: "Revenue per labor hour" },
  "Yfirvinna % af tímum": { is: "Yfirvinna % af tímum", en: "Overtime % of hours" },
  "Mætingahlutfall": { is: "Mætingahlutfall", en: "Attendance rate" },
  "Vaktaplan vs raun-tímar": { is: "Vaktaplan vs raun-tímar", en: "Schedule vs actual hours" },
  "áætlað á móti klukknuðum tímum — þessi vika vs fyrri vika": { is: "áætlað á móti klukknuðum tímum — þessi vika vs fyrri vika", en: "planned vs clocked hours — this week vs last week" },
  "Áætl. klst": { is: "Áætl. klst", en: "Plan hrs" },
  "Raun klst": { is: "Raun klst", en: "Actual hrs" },
  "Fyrri vika": { is: "Fyrri vika", en: "Last week" },
  "Raun kostn.": { is: "Raun kostn.", en: "Actual cost" },
  "Tímabanki starfsfólks": { is: "Tímabanki starfsfólks", en: "Staff time bank" },
  "uppsafnað +/− vs vinnuskylda": { is: "uppsafnað +/− vs vinnuskylda", en: "accrued +/− vs work obligation" },
  "Vinnuskylda": { is: "Vinnuskylda", en: "Work obligation" },
  "Unnið": { is: "Unnið", en: "Worked" },
  "Staða banka": { is: "Staða banka", en: "Bank balance" },
  "Skýrslusafn": { is: "Skýrslusafn", en: "Report library" },
  "smelltu til að sækja — PDF eða Excel": { is: "smelltu til að sækja — PDF eða Excel", en: "click to download — PDF or Excel" },

  // Performance
  "Júní 2026 vs maí 2026": { is: "Júní 2026 vs maí 2026", en: "June 2026 vs May 2026" },
  "Velta": { is: "Velta", en: "Revenue" },
  "Launakostnaður (byrði)": { is: "Launakostnaður (byrði)", en: "Labor cost (burden)" },
  "Framlegð": { is: "Framlegð", en: "Margin" },
  "Velta vs spá": { is: "Velta vs spá", en: "Revenue vs forecast" },
  "Unnið eftir áætlun": { is: "Unnið eftir áætlun", en: "Worked to plan" },
  "Launakostnaður": { is: "Launakostnaður", en: "Labor cost" },
  "Launakostn.": { is: "Launakostn.", en: "Labor cost" },
  "Laun%": { is: "Laun%", en: "Labor%" },
  "Laun% vs maí": { is: "Laun% vs maí", en: "Labor% vs May" },
  "Staður": { is: "Staður", en: "Location" },
  "Samanburður tímabila": { is: "Samanburður tímabila", en: "Period comparison" },
  "þetta tímabil · síðasta tímabil · sama tímabil í fyrra": { is: "þetta tímabil · síðasta tímabil · sama tímabil í fyrra", en: "this period · last period · same period last year" },
  "Mælikvarði": { is: "Mælikvarði", en: "Metric" },
  "Júní 2026": { is: "Júní 2026", en: "June 2026" },
  "Maí 2026": { is: "Maí 2026", en: "May 2026" },
  "Júní 2025": { is: "Júní 2025", en: "June 2025" },
  "Breyting (mán)": { is: "Breyting (mán)", en: "Change (mo)" },
  "vs í fyrra": { is: "vs í fyrra", en: "vs last year" },
  "Velta vs launakostnaður": { is: "Velta vs launakostnaður", en: "Revenue vs labor cost" },
  "6 mánuðir": { is: "6 mánuðir", en: "6 months" },
  "Laun% þróun vs 30% markmið": { is: "Laun% þróun vs 30% markmið", en: "Labor% trend vs 30% target" },
  "síðustu 6 mánuðir": { is: "síðustu 6 mánuðir", en: "last 6 months" },
  "Samanburður staða": { is: "Samanburður staða", en: "Location comparison" },
  "hver staður — velta, laun% og framlegð, breyting milli mánaða": { is: "hver staður — velta, laun% og framlegð, breyting milli mánaða", en: "each location — revenue, labor% and margin, month-on-month change" },
  "Greining eftir deild": { is: "Greining eftir deild", en: "Department breakdown" },
  "laun% per deild · júní": { is: "laun% per deild · júní", en: "labor% per department · June" },
  "Launasundurliðun": { is: "Launasundurliðun", en: "Pay breakdown" },
  "hvert peningarnir fara": { is: "hvert peningarnir fara", en: "where the money goes" },
  "perf:staff": { is: "Starfsfólk", en: "Staff" },
  "Ríkið": { is: "Ríkið", en: "Government" },
  "Sjóðir": { is: "Sjóðir", en: "Funds" },
  "perf:ai1": { is: " er yfir markmiði og versnar milli mánaða — yfirvinna í eldhúsi er drifkrafturinn. Næði Umi sama laun% og Reykjavík Asian myndi það skila ", en: " is over target and worsening month-on-month — kitchen overtime is the driver. If Umi reached the same labor% as Reykjavík Asian it would yield " },
  "perf:ai2": { is: " á mánuði.", en: " per month." },

  // Employee self-service (Mitt svæði)
  "Yfirlit": { is: "Yfirlit", en: "Overview" },
  "Mínar vaktir": { is: "Mínar vaktir", en: "My shifts" },
  "Laun": { is: "Laun", en: "Pay" },
  "Réttindi": { is: "Réttindi", en: "Rights" },
  "Prófíll": { is: "Prófíll", en: "Profile" },
  "emp:meta": { is: "Starfsmaður · Kaffi Krónan · Eldhús", en: "Employee · Kaffi Krónan · Eldhús" },
  "Á vakt síðan 08:02": { is: "Á vakt síðan 08:02", en: "On shift since 08:02" },
  "Ekki á vakt": { is: "Ekki á vakt", en: "Off shift" },
  "Stimpla út": { is: "Stimpla út", en: "Clock out" },
  "Stimpla inn": { is: "Stimpla inn", en: "Clock in" },
  "Næsta vakt": { is: "Næsta vakt", en: "Next shift" },
  "Verkefni vaktarinnar": { is: "Verkefni vaktarinnar", en: "Shift tasks" },
  "Opna kassa & kveikja á græjum": { is: "Opna kassa & kveikja á græjum", en: "Open the till & turn on equipment" },
  "Fylla á sósur og meðlæti": { is: "Fylla á sósur og meðlæti", en: "Refill sauces and sides" },
  "Þrífa grill fyrir lokun": { is: "Þrífa grill fyrir lokun", en: "Clean the grill before closing" },
  "Sækja um frí": { is: "Sækja um frí", en: "Request leave" },
  "Skipta á vakt": { is: "Skipta á vakt", en: "Swap shift" },
  "Opnar vaktir": { is: "Opnar vaktir", en: "Open shifts" },
  "Skrá framboð": { is: "Skrá framboð", en: "Set availability" },
  "Mitt vaktaplan · 22.–28. júní": { is: "Mitt vaktaplan · 22.–28. júní", en: "My schedule · 22–28 June" },
  "Samantekt": { is: "Samantekt", en: "Summary" },
  "Tímar vikunnar": { is: "Tímar vikunnar", en: "Hours this week" },
  "Tímar mánaðar (til þessa)": { is: "Tímar mánaðar (til þessa)", en: "Hours this month (so far)" },
  "Næsta útborgun": { is: "Næsta útborgun", en: "Next payout" },
  "Laun — júní 2026 (áætlað)": { is: "Laun — júní 2026 (áætlað)", en: "Pay — June 2026 (estimated)" },
  "Dagvinna": { is: "Dagvinna", en: "Day pay" },
  "Álög (kvöld/helgi)": { is: "Álög (kvöld/helgi)", en: "Premiums (evening/weekend)" },
  "Brúttó laun": { is: "Brúttó laun", en: "Gross pay" },
  "Lífeyrir 4% + félag 1%": { is: "Lífeyrir 4% + félag 1%", en: "Pension 4% + union 1%" },
  "Persónuafsláttur": { is: "Persónuafsláttur", en: "Personal allowance" },
  "Áætlað útborgað": { is: "Áætlað útborgað", en: "Estimated net pay" },
  "Fyrri mánuðir (útborgað)": { is: "Fyrri mánuðir (útborgað)", en: "Previous months (net paid)" },
  "Sækja launaseðil (PDF)": { is: "Sækja launaseðil (PDF)", en: "Download payslip (PDF)" },
  "Áunnir dagar": { is: "Áunnir dagar", en: "Accrued days" },
  "Nýttir í ár": { is: "Nýttir í ár", en: "Used this year" },
  "Orlofssjóður": { is: "Orlofssjóður", en: "Holiday fund" },
  "Tímabanki": { is: "Tímabanki", en: "Time bank" },
  "Vinnuskylda (mán)": { is: "Vinnuskylda (mán)", en: "Work obligation (mo)" },
  "Veikindi & réttindi": { is: "Veikindi & réttindi", en: "Sick leave & rights" },
  "Veikindadagar nýttir": { is: "Veikindadagar nýttir", en: "Sick days used" },
  "Starfshlutfall": { is: "Starfshlutfall", en: "Employment ratio" },
  "Hvíldartími (11 klst)": { is: "Hvíldartími (11 klst)", en: "Rest time (11 hrs)" },
  "Í lagi": { is: "Í lagi", en: "OK" },
  "Kjarasamningur": { is: "Kjarasamningur", en: "Union agreement" },
  "dagar": { is: "dagar", en: "days" },
  "Smelltu á myndina til að hlaða upp nýrri": { is: "Smelltu á myndina til að hlaða upp nýrri", en: "Click the photo to upload a new one" },
  "Fullt nafn": { is: "Fullt nafn", en: "Full name" },
  "Kennitala": { is: "Kennitala", en: "ID number" },
  "prof:position": { is: "Staða", en: "Position" },
  "Sími": { is: "Sími", en: "Phone" },
  "Netfang": { is: "Netfang", en: "Email" },
  "Bankareikningur (laun)": { is: "Bankareikningur (laun)", en: "Bank account (pay)" },
  "Vista breytingar": { is: "Vista breytingar", en: "Save changes" },
  "Frá": { is: "Frá", en: "From" },
  "Til": { is: "Til", en: "To" },
  "Tegund": { is: "Tegund", en: "Type" },
  "Frí (ólaunað)": { is: "Frí (ólaunað)", en: "Leave (unpaid)" },
  "Veikindi": { is: "Veikindi", en: "Sick leave" },
  "Senda beiðni": { is: "Senda beiðni", en: "Send request" },
  "Hakaðu við dagana sem þú getur unnið:": { is: "Hakaðu við dagana sem þú getur unnið:", en: "Tick the days you can work:" },
  "Vista framboð": { is: "Vista framboð", en: "Save availability" },
  "Vaktin þín": { is: "Vaktin þín", en: "Your shift" },
  "Skipta við": { is: "Skipta við", en: "Swap with" },
  "Hætta við": { is: "Hætta við", en: "Cancel" },
  "Sækja um": { is: "Sækja um", en: "Apply" },
  "Mán": { is: "Mán", en: "Mon" }, "Þri": { is: "Þri", en: "Tue" }, "Mið": { is: "Mið", en: "Wed" },
  "Fim": { is: "Fim", en: "Thu" }, "Fös": { is: "Fös", en: "Fri" }, "Lau": { is: "Lau", en: "Sat" }, "Sun": { is: "Sun", en: "Sun" },
  "req:leave:done": { is: "Frí-beiðni send — bíður samþykkis stjórnanda", en: "Leave request sent — awaiting manager approval" },
  "req:avail:done": { is: "Framboð vistað", en: "Availability saved" },
  "req:swap:done": { is: "Vaktaskipti-beiðni send — bíður samþykkis", en: "Shift swap request sent — awaiting approval" },

  // Schedule (Vaktaplan)
  "Afrita viku": { is: "Afrita viku", en: "Copy week" },
  "Birta plan": { is: "Birta plan", en: "Publish schedule" },
  "Þessi vika": { is: "Þessi vika", en: "This week" },
  "Biðja AI": { is: "Biðja AI", en: "Ask AI" },
  "Vakt": { is: "Vakt", en: "Shift" },
  "Vaktir í viku": { is: "Vaktir í viku", en: "Shifts this week" },
  "Stöðugildi (FTE)": { is: "Stöðugildi (FTE)", en: "FTE" },
  "Klst þann dag": { is: "Klst þann dag", en: "Hrs that day" },
  "Bæta starfsmanni á plan": { is: "Bæta starfsmanni á plan", en: "Add employee to plan" },
  "Vaktategundir": { is: "Vaktategundir", en: "Shift types" },
  "Dragðu vaktir milli reita — kostnaður uppfærist strax.": { is: "Dragðu vaktir milli reita — kostnaður uppfærist strax.", en: "Drag shifts between cells — cost updates instantly." },
  "AI-vaktaplan": { is: "AI-vaktaplan", en: "AI scheduling" },
  "segðu markmið — Vakto endurraðar": { is: "segðu markmið — Vakto endurraðar", en: "state a goal — Vakto reorganises" },
  "Tímar eftir dögum": { is: "Tímar eftir dögum", en: "Hours by day" },
  "áætlað í planinu · þessi vika": { is: "áætlað í planinu · þessi vika", en: "planned in the schedule · this week" },
  "Beiðnir & opnar vaktir": { is: "Beiðnir & opnar vaktir", en: "Requests & open shifts" },
  "frá starfsfólki — samþykktu eða úthlutaðu": { is: "frá starfsfólki — samþykktu eða úthlutaðu", en: "from staff — approve or assign" },
  "Á vakt": { is: "Á vakt", en: "On shift" },
  "Tímar dagsins": { is: "Tímar dagsins", en: "Hours today" },
  "Kostnaður dagsins": { is: "Kostnaður dagsins", en: "Cost today" },
  "Mönnunarþörf": { is: "Mönnunarþörf", en: "Staffing need" },
  "+ Bæta við vakt": { is: "+ Bæta við vakt", en: "+ Add shift" },
  "smelltu á vakt til að færa eða breyta": { is: "smelltu á vakt til að færa eða breyta", en: "click a shift to move or edit" },
  "Engar vaktir þennan dag.": { is: "Engar vaktir þennan dag.", en: "No shifts this day." },
  "smelltu á dag til að opna · á vakt til að breyta": { is: "smelltu á dag til að opna · á vakt til að breyta", en: "click a day to open · a shift to edit" },
  "Biðja AI um vaktaplan": { is: "Biðja AI um vaktaplan", en: "Ask AI for a schedule" },
  "Demo-tillaga — settu ANTHROPIC_API_KEY í .env.local fyrir alvöru AI-vaktaplan.": { is: "Demo-tillaga — settu ANTHROPIC_API_KEY í .env.local fyrir alvöru AI-vaktaplan.", en: "Demo proposal — set ANTHROPIC_API_KEY in .env.local for real AI scheduling." },
  "Lækka launakostnað um 10%": { is: "Lækka launakostnað um 10%", en: "Cut labor cost by 10%" },
  "haltu mönnun en lægri launum": { is: "haltu mönnun en lægri launum", en: "keep staffing but lower pay" },
  "Minnka yfirvinnu": { is: "Minnka yfirvinnu", en: "Reduce overtime" },
  "dreifa tímum, laga hvíld": { is: "dreifa tímum, laga hvíld", en: "spread hours, fix rest" },
  "Halda launum undir 30% af veltu": { is: "Halda launum undir 30% af veltu", en: "Keep labor under 30% of revenue" },
  "stilla mönnun að veltuspá": { is: "stilla mönnun að veltuspá", en: "match staffing to revenue forecast" },
  "keyra": { is: "keyra", en: "run" },
  "Samþykkja & birta": { is: "Samþykkja & birta", en: "Approve & publish" },
  "Breyta beiðni": { is: "Breyta beiðni", en: "Edit request" },
  "Búa til með AI": { is: "Búa til með AI", en: "Generate with AI" },
  "Tillaga AI": { is: "Tillaga AI", en: "AI proposal" },
  "Lýstu því sem þú vilt á venjulegri íslensku — VAKTO býr til vaktirnar og þú samþykkir.": { is: "Lýstu því sem þú vilt á venjulegri íslensku — VAKTO býr til vaktirnar og þú samþykkir.", en: "Describe what you want in plain language — VAKTO builds the shifts and you approve." },
  "Hafna": { is: "Hafna", en: "Reject" },
  "Úthluta": { is: "Úthluta", en: "Assign" },
  "skráð": { is: "skráð", en: "logged" },
  "4 ný": { is: "4 ný", en: "4 new" },
  "Ný vakt": { is: "Ný vakt", en: "New shift" },
  "sched:aiph": { is: "t.d. Settu Ómar á 2-2-3 vaktir 11:00–22:00 yfir allan maí", en: "e.g. Put Ómar on 2-2-3 shifts 11:00–22:00 throughout May" },
  "sched:ailoading": { is: "Bý til vaktatillögu sem virðir hvíldartíma, yfirvinnu og laun%…", en: "Building a shift proposal that respects rest time, overtime and labor%…" },
  "VAKTO hugsar…": { is: "VAKTO hugsar…", en: "VAKTO is thinking…" },
  "Bestun vaktaplans": { is: "Bestun vaktaplans", en: "Schedule optimization" },
  "Settu Ómar á 2-2-3 vaktir 11:00–22:00 yfir allan maí": { is: "Settu Ómar á 2-2-3 vaktir 11:00–22:00 yfir allan maí", en: "Put Ómar on 2-2-3 shifts 11:00–22:00 throughout May" },
  "Lágmarkaðu yfirvinnu í þessari viku": { is: "Lágmarkaðu yfirvinnu í þessari viku", en: "Minimize overtime this week" },
  "Mannaðu helgina með 2 í eldhúsi og 2 á sal": { is: "Mannaðu helgina með 2 í eldhúsi og 2 á sal", en: "Staff the weekend with 2 in the kitchen and 2 on the floor" },
  "Afritaðu þessa viku á næstu 4 vikur": { is: "Afritaðu þessa viku á næstu 4 vikur", en: "Copy this week to the next 4 weeks" },
  "Skilgreindu þínar eigin vaktategundir — heiti, tíma, álag og lit. Þær birtast í vaktaplaninu.": { is: "Skilgreindu þínar eigin vaktategundir — heiti, tíma, álag og lit. Þær birtast í vaktaplaninu.", en: "Define your own shift types — name, hours, premium and color. They appear in the schedule." },
  "+33% morgun/kvöld": { is: "+33% morgun/kvöld", en: "+33% morning/evening" },
  "+45% helgi": { is: "+45% helgi", en: "+45% weekend" },
  "+90% yfirvinna": { is: "+90% yfirvinna", en: "+90% overtime" },
  "Næturálag": { is: "Næturálag", en: "Night premium" },
  "Eyða": { is: "Eyða", en: "Delete" },
  "Búa til nýja vaktategund": { is: "Búa til nýja vaktategund", en: "Create new shift type" },
  "Heiti": { is: "Heiti", en: "Name" },
  "t.d. Næturvakt": { is: "t.d. Næturvakt", en: "e.g. Night shift" },
  "Upphaf": { is: "Upphaf", en: "Start" },
  "Lok": { is: "Lok", en: "End" },
  "Álag": { is: "Álag", en: "Premium" },
  "Litur": { is: "Litur", en: "Color" },
  "Bæta við": { is: "Bæta við", en: "Add" },
  "Loka": { is: "Loka", en: "Close" },
  "Veldu starfsmann til að bæta í vaktaplanið.": { is: "Veldu starfsmann til að bæta í vaktaplanið.", en: "Choose an employee to add to the schedule." },
  "+ bæta": { is: "+ bæta", en: "+ add" },
  "Vaktategund": { is: "Vaktategund", en: "Shift type" },
  "Sérsniðin vakt": { is: "Sérsniðin vakt", en: "Custom shift" },
  "Veldu tilbúna vaktategund eða stilltu tíma sjálf/ur. Vantar tegund?": { is: "Veldu tilbúna vaktategund eða stilltu tíma sjálf/ur. Vantar tegund?", en: "Pick a ready-made shift type or set the time yourself. Missing a type?" },
  "Búa til vaktategund": { is: "Búa til vaktategund", en: "Create shift type" },
  "Staða / dagur": { is: "Staða / dagur", en: "Position / day" },
  "Kokkur": { is: "Kokkur", en: "Cook" },
  "Þjónn / Sal": { is: "Þjónn / Sal", en: "Server / Floor" },
  "Bílstjóri": { is: "Bílstjóri", en: "Driver" },
  "Þú getur fært vaktina á annan dag eða starfsmann hér — eða dregið hana til í vikusýn.": { is: "Þú getur fært vaktina á annan dag eða starfsmann hér — eða dregið hana til í vikusýn.", en: "You can move the shift to another day or employee here — or drag it in the week view." },
  "Vista": { is: "Vista", en: "Save" },
  "Afrita": { is: "Afrita", en: "Copy" },
  "Fjarlægja af plani": { is: "Fjarlægja af plani", en: "Remove from plan" },
  "sh:Dagvakt": { is: "Dagvakt", en: "Day" },
  "sh:Morgun": { is: "Morgun", en: "Morning" },
  "sh:Mið": { is: "Mið", en: "Mid" },
  "sh:Kvöld": { is: "Kvöld", en: "Eve" },
  "Frí": { is: "Frí", en: "Off" },
  "frí": { is: "frí", en: "off" },
  "Sal": { is: "Sal", en: "Floor" },
  "Eldhús": { is: "Eldhús", en: "Kitchen" },
  "Stjórnun": { is: "Stjórnun", en: "Management" },
  "Dagvakt": { is: "Dagvakt", en: "Day shift" },
  "Morgunvakt": { is: "Morgunvakt", en: "Morning shift" },
  "Kvöldvakt": { is: "Kvöldvakt", en: "Evening shift" },
  "Helgarvakt": { is: "Helgarvakt", en: "Weekend shift" },
  "+33% fyrir 07:00": { is: "+33% fyrir 07:00", en: "+33% before 07:00" },
  "+33% álag": { is: "+33% álag", en: "+33% premium" },
  "+45% helgarálag": { is: "+45% helgarálag", en: "+45% weekend premium" },
  "Líma-hamur:": { is: "Líma-hamur:", en: "Paste mode:" },
  "smelltu á reiti til að líma": { is: "smelltu á reiti til að líma", en: "click cells to paste" },
  "Hætta": { is: "Hætta", en: "Cancel" },
  "á vakt": { is: "á vakt", en: "on shift" },
  "vaktir": { is: "vaktir", en: "shifts" },
  "Mánudagur": { is: "Mánudagur", en: "Monday" },
  "Þriðjudagur": { is: "Þriðjudagur", en: "Tuesday" },
  "Miðvikudagur": { is: "Miðvikudagur", en: "Wednesday" },
  "Fimmtudagur": { is: "Fimmtudagur", en: "Thursday" },
  "Föstudagur": { is: "Föstudagur", en: "Friday" },
  "Laugardagur": { is: "Laugardagur", en: "Saturday" },
  "Sunnudagur": { is: "Sunnudagur", en: "Sunday" },
  "júní": { is: "júní", en: "June" },
  "Þriðjudagur er þyngstur (62 klst) en laugardagur undirmannaður um hádegi — færðu eina vakt af þriðjudegi á laugardag.": { is: "Þriðjudagur er þyngstur (62 klst) en laugardagur undirmannaður um hádegi — færðu eina vakt af þriðjudegi á laugardag.", en: "Tuesday is heaviest (62 hrs) while Saturday is understaffed at midday — move one shift from Tuesday to Saturday." },
  "Frí-beiðni: Bach": { is: "Frí-beiðni: Bach", en: "Time-off request: Bach" },
  "27.–28. júní · orlof": { is: "27.–28. júní · orlof", en: "27–28 June · vacation" },
  "Vaktaskipti: Mína ↔ Phong": { is: "Vaktaskipti: Mína ↔ Phong", en: "Shift swap: Mína ↔ Phong" },
  "laugardagur 12–20 — báðir samþykktu": { is: "laugardagur 12–20 — báðir samþykktu", en: "Saturday 12–20 — both approved" },
  "Opin vakt: laugardag 12–20": { is: "Opin vakt: laugardag 12–20", en: "Open shift: Saturday 12–20" },
  "2 starfsmenn sóttu um — Ha Vu, Dalya": { is: "2 starfsmenn sóttu um — Ha Vu, Dalya", en: "2 employees applied — Ha Vu, Dalya" },
  "Óframboð: Ómar": { is: "Óframboð: Ómar", en: "Unavailability: Ómar" },
  "getur ekki unnið fimmtudaga í júlí": { is: "getur ekki unnið fimmtudaga í júlí", en: "can't work Thursdays in July" },
  "Heild:": { is: "Heild:", en: "Total:" },
  "velta": { is: "velta", en: "revenue" },
  "laun": { is: "laun", en: "labor" },
  "fleiri": { is: "fleiri", en: "more" },
  "opnar": { is: "opnar", en: "open" },
  "ný": { is: "ný", en: "new" },
  "starfsm.": { is: "starfsm.", en: "staff" },
  "starfsmenn": { is: "starfsmenn", en: "staff" },
  "grunntaxti": { is: "grunntaxti", en: "base rate" },
  "Tímar mánaðar": { is: "Tímar mánaðar", en: "Hours this month" },
  "Vaktir í dag": { is: "Vaktir í dag", en: "Shifts today" },
  "Vaktir í mánuði": { is: "Vaktir í mánuði", en: "Shifts this month" },
  "vs": { is: "vs", en: "vs" },
  "vs fyrri": { is: "vs fyrri", en: "vs previous" },
  "Vika 26 vs vika 25": { is: "Vika 26 vs vika 25", en: "Week 26 vs week 25" },
  "2. ársfj. vs 1. ársfj.": { is: "2. ársfj. vs 1. ársfj.", en: "Q2 vs Q1" },
  "2026 vs 2025": { is: "2026 vs 2025", en: "2026 vs 2025" },
  "Skrá veltu handvirkt": { is: "Skrá veltu handvirkt", en: "Enter revenue manually" },
  "án Inventra — sláðu inn veltu til að sjá laun vs velta": { is: "án Inventra — sláðu inn veltu til að sjá laun vs velta", en: "without Inventra — enter revenue to see labor vs revenue" },
  "slá inn": { is: "slá inn", en: "enter" },
  "Skrá veltu": { is: "Skrá veltu", en: "Enter revenue" },
  "Bæta við stað": { is: "Bæta við stað", en: "Add location" },
  "Ný staða": { is: "Ný staða", en: "New position" },
  "Bjóða notanda": { is: "Bjóða notanda", en: "Invite user" },
  "Heiti staðar": { is: "Heiti staðar", en: "Location name" },
  "Heiti stöðu": { is: "Heiti stöðu", en: "Position name" },
  "Grunntaxti (kr/klst)": { is: "Grunntaxti (kr/klst)", en: "Base rate (kr/hr)" },
  "Hlutverk (aðgangur)": { is: "Hlutverk (aðgangur)", en: "Role (access)" },
  "Velta (kr)": { is: "Velta (kr)", en: "Revenue (kr)" },
  "Dagsetning": { is: "Dagsetning", en: "Date" },
  "Sláðu inn veltu dagsins (eða tímabils) til að reikna laun% án Inventra.": { is: "Sláðu inn veltu dagsins (eða tímabils) til að reikna laun% án Inventra.", en: "Enter the day's (or period's) revenue to compute labor% without Inventra." },
  "Verktaki": { is: "Verktaki", en: "Contractor" },
  "Vaktstjóri": { is: "Vaktstjóri", en: "Shift lead" },

  // Chat screen
  "chat:channel": { is: "Tilkynningar — allir", en: "Announcements — everyone" },
  "chat:channelFull": { is: "Tilkynningar — allir starfsmenn", en: "Announcements — all staff" },
  "chat:send": { is: "Senda", en: "Send" },
  "chat:now": { is: "núna", en: "now" },

  // Settings audit
  "audit:title": { is: "Aðgerðaskrá", en: "Audit log" },
  "audit:sub": { is: "nýlegar breytingar í kerfinu", en: "recent changes in the system" },
  "audit:empty": { is: "Engar aðgerðir skráðar enn.", en: "No actions logged yet." },
};

const Ctx = createContext<{ lang: Lang; setLang: (l: Lang) => void }>({ lang: "is", setLang: () => {} });

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("is");
  useEffect(() => {
    // Default is "is" (matches SSR); only switch if the saved choice differs.
    if (localStorage.getItem("vakto-lang") === "en") {
      const id = requestAnimationFrame(() => setLangState("en"));
      return () => cancelAnimationFrame(id);
    }
  }, []);
  function setLang(l: Lang) {
    setLangState(l);
    try { localStorage.setItem("vakto-lang", l); } catch {}
  }
  return <Ctx.Provider value={{ lang, setLang }}>{children}</Ctx.Provider>;
}

export function useLang() {
  const { lang, setLang } = useContext(Ctx);
  const t = (key: string) => DICT[key]?.[lang] ?? key;
  return { lang, setLang, t };
}
