"use client";

import { createContext, useContext, useEffect, useState } from "react";

export type Lang = "is" | "en";

type Dict = Record<string, { is: string; en: string }>;

// App-shell chrome strings. Per-screen content can adopt useLang() incrementally.
export const DICT: Dict = {
  "grp:Dagleg vinna": { is: "Dagleg vinna", en: "Daily work" },
  "grp:Laun & fólk": { is: "Laun & fólk", en: "Payroll & HR" },
  "grp:Greining": { is: "Greiningar", en: "Analytics" },
  "grp:Starfsmaður": { is: "Starfsmaður", en: "Employee" },
  "nav:dashboard": { is: "Mælaborð", en: "Dashboard" },
  "nav:schedule": { is: "Vaktaplan", en: "Schedule" },
  "nav:attendance": { is: "Tímaskráning", en: "Time tracking" },
  "nav:payroll": { is: "Launakeyrslur", en: "Payroll" },
  "nav:employees": { is: "Starfsfólk", en: "Employees" },
  "nav:reports": { is: "Skýrslur", en: "Reports" },
  "nav:performance": { is: "Frammistaða", en: "Performance" },
  "nav:employeeapp": { is: "Starfsmannaapp", en: "Employee app" },
  "nav:chat": { is: "Spjallrásir", en: "Chat" },
  "nav:settings": { is: "Stillingar", en: "Settings" },
  "nav:help": { is: "Aðstoð", en: "Help" },
  search: { is: "Leita…", en: "Search…" },
  create: { is: "Stofna", en: "Create" },
  "create:shift": { is: "Ný vakt", en: "New shift" },
  "create:emp": { is: "Nýr starfsmaður", en: "New employee" },
  "create:plan": { is: "Nýtt vaktaplan", en: "New schedule" },
  "create:loc": { is: "Ný starfsstöð", en: "New location" },
  notifications: { is: "Tilkynningar", en: "Notifications" },
  seeall: { is: "Sjá allar →", en: "See all →" },
  "acct:role": { is: "Skipta um hlutverk", en: "Switch role / access" },
  "acct:loc": { is: "Velja fyrirtæki / stað", en: "Choose company / location" },
  "acct:kiosk": { is: "Stimpilklukka (Kiosk)", en: "Time clock (kiosk)" },
  "acct:settings": { is: "Stillingar", en: "Settings" },
  "acct:help": { is: "Aðstoð", en: "Help" },
  "acct:dark": { is: "Dökkt útlit", en: "Dark mode" },
  "Ljóst útlit": { is: "Ljóst útlit", en: "Light mode" },
  "Dökkt útlit virkt": { is: "Dökkt útlit virkt", en: "Dark mode enabled" },
  "Ljóst útlit virkt": { is: "Ljóst útlit virkt", en: "Light mode enabled" },
  "Velkomin í VAKTO": { is: "Velkomin í VAKTO", en: "Welcome to VAKTO" },
  "Rauntölur úr þínum gögnum": { is: "Rauntölur úr þínum gögnum", en: "Live data feed" },
  "Nánari greiningar — gröf, frávik og samanburður — birtast eftir því sem vaktir, stimplanir og velta safnast. Sjá Tímaskráning, Skýrslur og Frammistöðu.": { is: "Ítarlegri greiningar, myndrit, frávik og samanburður birtast jafnóðum og vaktir, stimplanir og velta safnast í kerfið. Sjá Tímaskráningu, Skýrslur og Frammistöðu.", en: "Advanced analytics, charts, variances, and operational comparisons will populate automatically as shifts, time logs, and revenue stack up." },
  "Engin tímaskráning enn": { is: "Engin tímaskráning enn", en: "No time records yet" },
  "Tímaskráning birtist hér um leið og starfsfólk byrjar að stimpla inn — gegnum appið eða Kiosk-skjáinn. Bættu fyrst við starfsfólki.": { is: "Tímaskráningar munu birtast hér um leið og starfsfólk stimplar sig inn í gegnum appið eða Kiosk-skjáinn. Byrjaðu á því að bæta við starfsfólki.", en: "Time tracking entries will appear here as soon as team members clock in via the app or Kiosk. Add your staff to get started." },
  "Engar skýrslur enn": { is: "Engar skýrslur enn", en: "No reports generated yet" },
  "Skýrslur byggja á vöktum, tímaskráningu og launakeyrslum. Bættu við starfsfólki og birtu vaktaplan — þá fyllast greiningarnar sjálfkrafa.": { is: "Skýrslur byggja á vöktum, tímaskráningu og launakeyrslum. Bættu við starfsfólki og birtu vaktaplan til að virkja greiningarnar sjálfkrafa.", en: "Reports are built from scheduled shifts, actual logs, and completed payroll. Populate your staff and publish a schedule to begin tracking." },
  "Engin frammistöðugögn enn": { is: "Engin frammistöðugögn enn", en: "No performance data yet" },
  "Þróun, framlegð og laun% birtast hér þegar þú ert komin/n með veltu og launakeyrslur. Byrjaðu á að bæta við starfsfólki og skrá veltu.": { is: "Söguleg þróun, framlegð og launahlutfall birtast hér þegar velta og launakeyrslur liggja fyrir. Byrjaðu á að skrá veltu og bæta við starfsfólki.", en: "Operational trends, margins, and labor% metrics will appear here once revenue data and payroll are active." },
  "Engar launakeyrslur enn": { is: "Engar launakeyrslur enn", en: "No payroll runs yet" },
  "Bættu fyrst við starfsfólki með taxta og kjarasamningi. Þá getur þú keyrt launakeyrslu sem VAKTO reiknar sjálfkrafa og Payday sér um skil.": { is: "Bættu fyrst við starfsfólki með launataxta og kjarasamningi. Því næst getur þú framkvæmt launakeyrslu sem VAKTO reiknar sjálfkrafa og samþættir við Payday.", en: "First, assign pay rates and union agreements to staff. Then, generate automated payroll calculated by VAKTO and directly exported via Payday." },
  "engin gögn": { is: "engin gögn", en: "no data available" },
  "Vantar stimplun": { is: "Stimplun vantar", en: "Missing punch" },
  "Á áætlun": { is: "Á áætlun", en: "On track" },
  "Skráðu veltu (eða tengdu Inventra) til að sjá laun af tekjum og framlegð. Launakostnaður reiknast af starfsfólki og kjarasamningum.": { is: "Skráðu veltu handvirkt eða tengdu Inventra til að fylgjast með launahlutfalli og framlegð. Launakostnaður miðast við kjarasamninga starfsfólks.", en: "Log revenue manually or link Inventra to track labor% and margin. Labor costs are calculated based on customized employee union metrics." },
  "Söguleg þróun og samanburður tímabila birtist eftir því sem fleiri launatímabil og veltutölur safnast.": { is: "Söguleg þróun og samanburður á milli rekstrartímabila birtist hér eftir því sem fleiri launatímabil og veltutölur safnast í kerfið.", en: "Historical trends and comprehensive period comparisons will unfold as sequential payroll cycles and revenue history accumulate." },
  "Engar nýjar tilkynningar": { is: "Engar nýjar tilkynningar", en: "No new notifications" },
  "Kiosk-stimpilklukka": { is: "Kiosk-stimpilklukka", en: "Kiosk Time Clock" },
  "opnaðu á spjaldtölvu — PIN = síðustu 4 í kennitölu · smelltu til að afrita slóð": { is: "Opnaðu á spjaldtölvu — PIN = síðustu 4 tölustafir í kennitölu · Smelltu til að afrita hlekk", en: "Open on a tablet station — PIN = last 4 digits of ID number (kennitala) · Click to copy link" },
  "afrita slóð": { is: "afrita slóð", en: "Copy link" },
  "Launareglur kjarasamninga": { is: "Launareglur kjarasamninga", en: "Union pay rules" },
  "álag, yfirvinna og stórhátíðardagar — smelltu til að staðfesta": { is: "Vaktaálög, yfirvinna og stórhátíðardagar — Smelltu til að staðfesta", en: "Premiums, overtime, and public holiday logs — Click to confirm" },
  "staðfest": { is: "Staðfest", en: "Confirmed" },
  "óstaðfest": { is: "Óstaðfest", en: "Unconfirmed" },
  "yfirvinna": { is: "Yfirvinna", en: "Overtime" },
  "stórhátíð": { is: "Stórhátíðardagur", en: "Public holiday" },
  "Kvöld-/morgunálag": { is: "Kvöld-/morgunálag", en: "Evening/morning premium" },
  "Helgarálag": { is: "Helgarálag", en: "Weekend premium" },
  "Stórhátíðarálag": { is: "Stórhátíðarálag", en: "Public holiday premium" },
  "Álag / yfirvinna (%)": { is: "Álag / yfirvinna (%)", en: "Premium / Overtime (%)" },
  "Ég staðfesti að þetta stemmir við kjarasamninginn": { is: "Ég staðfesti að þetta samræmist viðkomandi kjarasamningi", en: "I confirm this complies with the active union agreement" },
  "Berðu saman við réttan samning (Efling/VR/SGS) áður en þú staðfestir.": { is: "Berið saman við viðeigandi kjarasamning (Efling / VR / SGS) áður en gengið er frá staðfestingu.", en: "Verify accuracy against the official agreement template (Efling/VR/SGS) before confirmation." },
  "⚠️ Prósenturnar eru staðlað sniðmát — staðfestu hverja gegn raunverulegum kjarasamningi (Efling/VR) áður en þær eru notaðar á laun.": { is: "⚠️ Prósenturnar eru staðlað viðmiðunarsniðmát — Samræmdu prósentur við gildandi kjarasamninga (Efling / VR) áður en laun eru keyrð.", en: "⚠️ Percentages are based on general templates — Ensure exact compliance with the actual union agreement (Efling/VR) prior to processing payroll." },
  "af 4 skrefum kláruð — settu kerfið upp á nokkrum mínútum.": { is: "af 4 skrefum lokið — Uppsetning klárast á nokkrum mínútum.", en: "of 4 configuration steps completed — Set up the platform in minutes." },
  "Skrá veltu / tengja Inventra": { is: "Skrá veltu / tengja Inventra", en: "Log revenue / Connect Inventra" },
  "Þegar þú hefur bætt við starfsfólki og birt vaktaplan birtast hér lifandi tölur — laun af tekjum, launakostnaður, frávik og yfirvinna.": { is: "Þegar starfsfólki hefur verið bætt við og vaktaplan gefið út uppfærast rauntölur hér: Launahlutfall, raunkostnaður, frávik og yfirvinnustundir.", en: "Once personnel are added and a schedule is published, live metrics like labor% of revenue, labor burden, variances, and overtime tracking will appear here." },
  "acct:logout": { is: "Útskráning", en: "Sign out" },
  "role:owner": { is: "Eigandi", en: "Owner" },
  "role:manager": { is: "Rekstrarstjóri", en: "Manager" },
  "role:employee": { is: "Starfsmaður", en: "Employee" },
  "role:contractor": { is: "Verktaki", en: "Contractor" },
  "chat:title": { is: "Aðstoð VAKTO", en: "VAKTO Support" },
  "chat:sub": { is: "Við svörum yfirleitt innan fárra mínútna", en: "We typically reply within a few minutes" },
  "chat:hi": { is: "Hæ! Hvernig getum við aðstoðað þig í dag?", en: "Hi! How can we help you today?" },
  "chat:hint": { is: "Þú getur spurt um vaktaplön, launakeyrslur, kjarasamninga eða samþættingar.", en: "Ask about scheduling automation, payroll processing, union tracking, or system integrations." },
  "chat:ph": { is: "Skrifaðu skilaboð hér…", en: "Type a message…" },
  "cookie:h": { is: "Við notum vafrakökur", en: "We use cookies" },
  "cookie:p": { is: "Til að bæta upplifun notenda, greina umferð og birta viðeigandi efni.", en: "To optimize user experience, analyze traffic patterns, and deliver relevant interface content." },
  "cookie:more": { is: "Nánari upplýsingar um vafrakökur", en: "Cookie policy details" },
  "cookie:allow": { is: "Samþykkja allar", en: "Allow all" },
  "cookie:deny": { is: "Hafna öllum", en: "Reject all" },
  "cookie:settings": { is: "Umsýsla vafrakakna", en: "Cookie configurations" },

  // page-header titles (keyed by the Icelandic string)
  "Mælaborð": { is: "Mælaborð", en: "Dashboard" },
  "Vaktaplan": { is: "Vaktaplan", en: "Schedule" },
  "Tímaskráning": { is: "Tímaskráning", en: "Time tracking" },
  "Launakeyrslur": { is: "Launakeyrslur", en: "Payroll" },
  "Starfsfólk": { is: "Starfsfólk", en: "Employees" },
  "Skýrslur": { is: "Skýrslur", en: "Reports" },
  "Frammistaða": { is: "Frammistaða", en: "Performance" },
  "Mitt svæði": { is: "Mitt svæði", en: "My area" },
  "Spjall": { is: "Spjallrásir", en: "Chat" },
  "Stillingar": { is: "Stillingar", en: "Settings" },
  // page-header subtitles
  "Þriðjudagur 23. júní 2026": { is: "Þriðjudagur 23. júní 2026", en: "Tuesday 23 June 2026" },
  "Vika 22.–28. júní 2026": { is: "Vika 22.–28. júní 2026", en: "Week 22–28 June 2026" },
  "Áætlað vs raun · þessi vika": { is: "Áætlað vs. raun · Þessi vika", en: "Planned vs. actual · This week" },
  "Launagreiðslur · 2026": { is: "Launagreiðslur · 2026", en: "Payroll runs · 2026" },
  "Greiningar og frammistaða": { is: "Greiningar og frammistaða", en: "Analytics and performance" },
  "Þróun, framlegð og launasundurliðun": { is: "Þróun rekstrar, framlegð og launasundurliðun", en: "Operational trends, margin and labor breakdowns" },
  "Vaktir, laun, réttindi og prófíll": { is: "Vaktir, launamál, réttindi og notendaprófíll", en: "Shifts, earnings, employment rights and profile" },
  "Skilaboð til starfsfólks og stjórnenda": { is: "Skilaboð til starfsfólks og stjórnenda", en: "Internal messages to team and management" },
  "Reglur, kjarasamningar og tengingar": { is: "Launareglur, kjarasamningar og kerfistengingar", en: "Operational rules, union compliance and integrations" },

  // Starfsfólk screen
  "emp:new": { is: "+ Nýr starfsmaður", en: "+ New employee" },
  "emp:kpi:count": { is: "Heildarfjöldi starfsmanna", en: "Total employees" },
  "emp:kpi:fte": { is: "Stöðugildi (FTE)", en: "FTE equivalents" },
  "emp:kpi:over": { is: "Yfir starfshlutfalli", en: "Over employment ratio" },
  "emp:kpi:leave": { is: "Í leyfi þessa viku", en: "On leave this week" },
  "emp:card": { is: "Starfsfólk & snið", en: "Employee profiles" },
  "emp:card:sub": { is: "Sérhver starfsmaður geymir eigin launaprófíl — launataxta, kjarasamning, álög og frádráttarliði", en: "Each employee holds a dedicated pay profile — baseline rates, union mappings, premiums, and active deductions" },
  "emp:th:name": { is: "Nafn", en: "Name" },
  "emp:th:dept": { is: "Deild", en: "Department" },
  "emp:th:type": { is: "Launaform", en: "Type" },
  "emp:th:rate": { is: "Taxti", en: "Pay rate" },
  "emp:th:ratio": { is: "Starfshlutfall", en: "Ratio" },
  "emp:th:union": { is: "Kjarasamningur", en: "Union agreement" },
  "emp:th:status": { is: "Staða", en: "Status" },
  "emp:hourly": { is: "Tímakaup", en: "Hourly" },
  "emp:monthly": { is: "Mánaðarlaun", en: "Monthly" },
  "emp:active": { is: "Í starfi", en: "Active" },
  "emp:overtime": { is: "Yfirvinna", en: "Overtime" },
  "emp:overratio": { is: "Yfir starfshlutfalli", en: "Over ratio" },
  "emp:subtitle": { is: "starfsmenn skráðir", en: "employees registered" },
  "emp:fteword": { is: "stöðugildi samtals", en: "total FTE" },
  "emp:footer": { is: "Smelltu á starfsmann til að uppfæra taxta, álög og samninga, eða til að hlaða inn tilbúnum kjarasamningi.", en: "Select an employee to manage pay structures and union configurations, or instantly apply a standard contract template." },
  "emp:demo": { is: " · (Prófunargögn — Tengdu gagnagrunn til að virkja rauntölur)", en: " · (Demo environment data — Connect live backend database for accurate figures)" },
  "emp:shows": { is: "Sýnir", en: "Showing" },
  "Flytja inn (Excel)": { is: "Flytja inn (Excel)", en: "Import (Excel)" },
  "Flyt inn…": { is: "Flyt inn…", en: "Importing…" },

  // shared words
  "klst": { is: "klst", en: "hrs" },
  "stig": { is: "stig", en: "pts" },
  "Vika": { is: "Vika", en: "Week" },
  "Dagur": { is: "Dagur", en: "Day" },
  "Mánuður": { is: "Mánuður", en: "Month" },
  "Ár": { is: "Ár", en: "Year" },
  "Sækja PDF": { is: "Sækja PDF", en: "Download PDF" },
  "Eyða vakt": { is: "Eyða vakt", en: "Delete shift" },
  "Rauntölur uppfærast eftir því sem stimplað er inn og út.": { is: "Rauntölur uppfærast eftir því sem stimplað er inn og út.", en: "Live figures update as staff clock in and out." },
  "Launakostnaður vikunnar": { is: "Launakostnaður vikunnar", en: "This week's labor cost" },
  "Skráðu veltu til að sjá laun%": { is: "Skráðu veltu til að sjá laun%", en: "Enter revenue to see labor %" },
  "Samanburðargröf birtast þegar fleiri tímabil safnast.": { is: "Samanburðargröf birtast þegar fleiri tímabil safnast.", en: "Comparison charts appear as more periods accrue." },
  "Frávik birtast þegar starfsfólk stimplar inn og út.": { is: "Frávik birtast þegar starfsfólk stimplar inn og út.", en: "Deviations appear once staff clock in and out." },
  "Engin atriði krefjast athygli núna.": { is: "Engin atriði krefjast athygli núna.", en: "Nothing needs attention right now." },
  "Mánaðaryfirlit": { is: "Mánaðaryfirlit", en: "Monthly overview" },
  "Mánaðarsamanburður birtist þegar fleiri tímabil og launakeyrslur safnast.": { is: "Mánaðarsamanburður birtist þegar fleiri tímabil og launakeyrslur safnast.", en: "Monthly comparison appears as more periods and payroll runs accrue." },
  "skráðir inn — leiðréttu tíma eða stimplaðu út": { is: "skráðir inn — leiðréttu tíma eða stimplaðu út", en: "clocked in — correct times or clock out" },
  "skráðir inn í rauntíma": { is: "skráðir inn í rauntíma", en: "clocked in, in real time" },
  "Stimpla inn starfsmann": { is: "Stimpla inn starfsmann", en: "Clock in employee" },
  "tk:clockin": { is: "Stimpla inn", en: "Clock in" },
  "tk:clockout": { is: "Stimpla út", en: "Clock out" },
  "Tímaskráningar": { is: "Tímaskráningar", en: "Time records" },
  "Til baka": { is: "Til baka", en: "Back" },
  "Allar skráningar": { is: "Allar skráningar", en: "All records" },
  "Bíða samþykkis": { is: "Bíða samþykkis", en: "Awaiting approval" },
  "Vaktir": { is: "Vaktir", en: "Shifts" },
  "Opna á heilli síðu": { is: "Opna á heilli síðu", en: "Open full page" },
  "bíða samþykkis": { is: "bíða samþykkis", en: "awaiting approval" },
  "Samþykkja allar": { is: "Samþykkja allar", en: "Approve all" },
  "vaktir samþykktar": { is: "vaktir samþykktar", en: "shifts approved" },
  "Klst": { is: "Klst", en: "Hrs" },
  "opin": { is: "opin", en: "open" },
  "Samþykkt": { is: "Samþykkt", en: "Approved" },
  "Bíður": { is: "Bíður", en: "Pending" },
  "Afturkalla": { is: "Afturkalla", en: "Revoke" },
  "Engar skráningar á þessu tímabili.": { is: "Engar skráningar á þessu tímabili.", en: "No records for this period." },
  "Hleð…": { is: "Hleð…", en: "Loading…" },
  "Keyrðu migration 0008 í Supabase til að virkja samþykki.": { is: "Keyrðu migration 0008 í Supabase til að virkja samþykki.", en: "Run migration 0008 in Supabase to enable approvals." },
  "Leiðrétta": { is: "Leiðrétta", en: "Correct" },
  "Leiðrétta tíma": { is: "Leiðrétta tíma", en: "Correct times" },
  "breyttu inn- eða útstimplun": { is: "breyttu inn- eða útstimplun", en: "edit clock-in or clock-out" },
  "Innstimplun": { is: "Innstimplun", en: "Clock-in" },
  "Útstimplun": { is: "Útstimplun", en: "Clock-out" },
  "Tími innstimplunar": { is: "Tími innstimplunar", en: "Clock-in time" },
  "Skildu útstimplun eftir auða til að halda vaktinni opinni.": { is: "Skildu útstimplun eftir auða til að halda vaktinni opinni.", en: "Leave clock-out empty to keep the shift open." },
  "fyrir einhvern sem gleymdi að skrá sig inn": { is: "fyrir einhvern sem gleymdi að skrá sig inn", en: "for someone who forgot to clock in" },
  "Allir eru þegar skráðir inn": { is: "Allir eru þegar skráðir inn", en: "Everyone is already clocked in" },
  "Enginn skráður inn núna.": { is: "Enginn skráður inn núna.", en: "Nobody is clocked in right now." },
  "inn": { is: "inn", en: "in" },
  "handvirkt": { is: "handvirkt", en: "manual" },
  "Í gær": { is: "Í gær", en: "Yesterday" },
  "Skírteini": { is: "Skírteini", en: "ID card" },
  "Fast (kr/mán)": { is: "Fast (kr/mán)", en: "Fixed (kr/mo)" },
  "Per km": { is: "Per km", en: "Per km" },
  "Upphæð": { is: "Upphæð", en: "Amount" },
  "Föst hlunnindi bætast við laun. Per-km (t.d. ökutækjastyrkur) reiknast af skráðum km.": { is: "Föst hlunnindi bætast við laun. Per-km (t.d. ökutækjastyrkur) reiknast af skráðum km.", en: "Fixed benefits are added to pay. Per-km (e.g. vehicle allowance) is calculated from logged km." },
  "Engin hlunnindi skráð — bættu við einu eða fleiri hér að neðan.": { is: "Engin hlunnindi skráð — bættu við einu eða fleiri hér að neðan.", en: "No benefits yet — add one or more below." },
  "Ekki mætt af plani": { is: "Ekki mætt af plani", en: "Not clocked in" },
  "á plani í dag en ekki stimplaðir inn": { is: "á plani í dag en ekki stimplaðir inn", en: "scheduled today but not clocked in" },
  "seinir": { is: "seinir", en: "late" },
  "á plani": { is: "á plani", en: "scheduled" },
  "of seint": { is: "of seint", en: "late" },
  "væntanleg/ur": { is: "væntanleg/ur", en: "upcoming" },
  "Allir á plani hafa mætt.": { is: "Allir á plani hafa mætt.", en: "Everyone on the plan has clocked in." },
  "Yfirvinna tekur við": { is: "Yfirvinna tekur við", en: "Overtime starts" },
  "Eftir klst/viku": { is: "Eftir klst/viku", en: "After hrs/week" },
  "Eftir klst/mánuði": { is: "Eftir klst/mánuði", en: "After hrs/month" },
  "t.d. 40": { is: "t.d. 40", en: "e.g. 40" },
  "0 = óvirkt, t.d. 173,3": { is: "0 = óvirkt, t.d. 173,3", en: "0 = off, e.g. 173.3" },
  "Þegar unnar stundir fara yfir mörkin reiknast yfirvinnu-% (að ofan).": { is: "Þegar unnar stundir fara yfir mörkin reiknast yfirvinnu-% (að ofan).", en: "Hours beyond the threshold are paid at the overtime % (above)." },
  "Sérálög á tímabili": { is: "Sérálög á tímabili", en: "Custom time-based premiums" },
  "Engin sérálög — bættu við t.d. „kvöld 18–23 +33%\" eða „sunnudagar +45%\".": { is: "Engin sérálög — bættu við t.d. „kvöld 18–23 +33%\" eða „sunnudagar +45%\".", en: "No custom premiums — add e.g. \"evenings 18–23 +33%\" or \"Sundays +45%\"." },
  "Heiti (valfrjálst)": { is: "Heiti (valfrjálst)", en: "Label (optional)" },
  "Sérálög leggjast ofan á grunnreglurnar — hæsta % gildir á hverri stundu. Mundu að ýta á Vista.": { is: "Sérálög leggjast ofan á grunnreglurnar — hæsta % gildir á hverri stundu. Mundu að ýta á Vista.", en: "Custom premiums stack on the base rules — the highest % applies each hour. Remember to Save." },
  "Desember- & orlofsuppbót": { is: "Desember- & orlofsuppbót", en: "December & holiday bonus" },
  "úr kjarasamningi": { is: "úr kjarasamningi", en: "from the agreement" },
  "eigin samningur": { is: "eigin samningur", en: "custom agreement" },
  "Orlofsuppbót": { is: "Orlofsuppbót", en: "Holiday bonus" },
  "Desemberuppbót": { is: "Desemberuppbót", en: "December bonus" },
  "greidd 1. júní": { is: "greidd 1. júní", en: "paid June 1" },
  "greidd 1. desember": { is: "greidd 1. desember", en: "paid Dec 1" },
  "Hlutfallað eftir starfshlutfalli": { is: "Hlutfallað eftir starfshlutfalli", en: "Prorated by employment ratio" },
  "Greiðist sjálfkrafa í launakeyrslu réttan mánuð. (Upphæðir óstaðfestar — yfirfarið gegn samningi.)": { is: "Greiðist sjálfkrafa í launakeyrslu réttan mánuð. (Upphæðir óstaðfestar — yfirfarið gegn samningi.)", en: "Paid automatically in the payroll run for that month. (Amounts unconfirmed — verify against the agreement.)" },
  "undanþegið staðgr.": { is: "undanþegið staðgr.", en: "tax-exempt" },
  "Staðgr.skylt": { is: "Staðgr.skylt", en: "Taxable" },
  "Undanþegið": { is: "Undanþegið", en: "Tax-exempt" },
  "Ný grúppa": { is: "Ný grúppa", en: "New group" },
  "Leita": { is: "Leita", en: "Search" },
  "Nýtt spjall": { is: "Nýtt spjall", en: "New chat" },
  "Bein skilaboð": { is: "Bein skilaboð", en: "Direct message" },
  "Upplýsingar": { is: "Upplýsingar", en: "Details" },
  "Veldu spjall": { is: "Veldu spjall", en: "Select a conversation" },
  "Tákn": { is: "Tákn", en: "Emoji" },
  "Talskilaboð": { is: "Talskilaboð", en: "Voice message" },
  "Tek upp… smelltu til að stöðva": { is: "Tek upp… smelltu til að stöðva", en: "Recording… tap to stop" },
  "Veldu meðlimi": { is: "Veldu meðlimi", en: "Select members" },
  "Búa til grúppu": { is: "Búa til grúppu", en: "Create group" },
  "t.d. Eldhús, Kvöldvakt…": { is: "t.d. Eldhús, Kvöldvakt…", en: "e.g. Kitchen, Evening shift…" },
  "Meðlimir": { is: "Meðlimir", en: "Members" },
  "Bæta við fólki": { is: "Bæta við fólki", en: "Add people" },
  "stofnandi": { is: "stofnandi", en: "owner" },
  "Fjarlægja": { is: "Fjarlægja", en: "Remove" },
  "Hætta í grúppu": { is: "Hætta í grúppu", en: "Leave group" },
  "Spjallið virkjast þegar þú ert innskráð/ur og Supabase er tengt (migrations 0012 + 0014).": { is: "Spjallið virkjast þegar þú ert innskráð/ur og Supabase er tengt (migrations 0012 + 0014).", en: "Chat activates when you're signed in and Supabase is connected (migrations 0012 + 0014)." },
  "Heiti grúppu": { is: "Heiti grúppu", en: "Group name" },
  "Grúppa": { is: "Grúppa", en: "Group" },
  "Allir í fyrirtækinu": { is: "Allir í fyrirtækinu", en: "Everyone at the company" },
  "Engin skilaboð enn — byrjaðu spjallið!": { is: "Engin skilaboð enn — byrjaðu spjallið!", en: "No messages yet — start the conversation!" },
  "Ég": { is: "Ég", en: "Me" },
  "Mönnun & þörf": { is: "Mönnun & þörf", en: "Staffing & need" },
  "á vakt á móti mönnunarþörf · þessi vika": { is: "á vakt á móti mönnunarþörf · þessi vika", en: "on shift vs staffing need · this week" },
  "Stilla þörf": { is: "Stilla þörf", en: "Set need" },
  "Mönnunarþörf á viku": { is: "Mönnunarþörf á viku", en: "Weekly staffing need" },
  "Hversu marga þarf á vakt hvern dag? VAKTO sýnir vöntun í planinu.": { is: "Hversu marga þarf á vakt hvern dag? VAKTO sýnir vöntun í planinu.", en: "How many are needed on shift each day? VAKTO flags shortfalls in the schedule." },
  "Leiðréttingabeiðnir": { is: "Leiðréttingabeiðnir", en: "Correction requests" },
  "frá starfsfólki — samþykktu eða hafnaðu": { is: "frá starfsfólki — samþykktu eða hafnaðu", en: "from staff — approve or reject" },
  "út": { is: "út", en: "out" },
  "Mínir unnir tímar · þessi mánuður": { is: "Mínir unnir tímar · þessi mánuður", en: "My worked hours · this month" },
  "Óska eftir leiðréttingu": { is: "Óska eftir leiðréttingu", en: "Request correction" },
  "Engar stimplanir í þessum mánuði enn.": { is: "Engar stimplanir í þessum mánuði enn.", en: "No punches this month yet." },
  "Stimplanir birtast hér þegar þú stimplar inn/út.": { is: "Stimplanir birtast hér þegar þú stimplar inn/út.", en: "Your punches appear here once you clock in/out." },
  "t.d. gleymdi að stimpla inn eða út": { is: "t.d. gleymdi að stimpla inn eða út", en: "e.g. forgot to clock in or out" },
  "Réttur tími inn": { is: "Réttur tími inn", en: "Correct clock-in" },
  "Réttur tími út": { is: "Réttur tími út", en: "Correct clock-out" },
  "Skýring": { is: "Skýring", en: "Reason" },
  "t.d. gleymdi að stimpla út kl. 16": { is: "t.d. gleymdi að stimpla út kl. 16", en: "e.g. forgot to clock out at 16:00" },
  "Fyrirtæki": { is: "Fyrirtæki", en: "Company" },
  "Kt. fyrirtækis": { is: "Kt. fyrirtækis", en: "Company ID no." },
  "Skírteinisnr.": { is: "Skírteinisnr.", en: "Card no." },
  "Starfsmannaskírteini": { is: "Starfsmannaskírteini", en: "Staff ID card" },
  "Sýndu kóðann við innstimplun eða auðkenningu": { is: "Sýndu kóðann við innstimplun eða auðkenningu", en: "Show this code to clock in or identify" },
  "Apple Wallet": { is: "Apple Wallet", en: "Apple Wallet" },
  "Google Wallet": { is: "Google Wallet", en: "Google Wallet" },
  "Wallet er ekki uppsett enn": { is: "Wallet er ekki uppsett enn", en: "Wallet is not set up yet" },
  "Síðasti mánuður": { is: "Síðasti mánuður", en: "Last month" },
  "Samþykktir tímar": { is: "Samþykktir tímar", en: "Approved hours" },
  "aðeins samþykktir tímar": { is: "aðeins samþykktir tímar", en: "approved hours only" },
  "Engir samþykktir tímar á þessu tímabili — samþykktu vaktir í Tímaskráningu.": { is: "Engir samþykktir tímar á þessu tímabili — samþykktu vaktir í Tímaskráningu.", en: "No approved hours in this period — approve shifts in Time tracking." },
  "Keyrðu migration 0008 — núna teljast allir lokaðir tímar, ekki bara samþykktir.": { is: "Keyrðu migration 0008 — núna teljast allir lokaðir tímar, ekki bara samþykktir.", en: "Run migration 0008 — currently all closed punches count, not only approved." },
  "db:vika": { is: "Þessi vika", en: "This week" },
  "7 dagar": { is: "7 dagar", en: "7 days" },
  "30 dagar": { is: "30 dagar", en: "30 days" },
  "Sérsniðið": { is: "Sérsniðið", en: "Custom" },
  "Sérsniðið tímabil": { is: "Sérsniðið tímabil", en: "Custom period" },
  "Án samanburðar": { is: "Án samanburðar", en: "No comparison" },
  "Enginn starfsmaður fannst": { is: "Enginn starfsmaður fannst", en: "No employee found" },
  "Í fyrra": { is: "Í fyrra", en: "Last year" },
  "Fyrri tímabil": { is: "Fyrri tímabil", en: "Previous period" },
  "tímabil": { is: "tímabil", en: "period" },
  "Bera saman við": { is: "Bera saman við", en: "Compare with" },
  "Enginn samanburður": { is: "Enginn samanburður", en: "No comparison" },
  "Sama tímabil í fyrra": { is: "Sama tímabil í fyrra", en: "Same period last year" },
  "vantar stimplun": { is: "vantar stimplun", en: "missing punch" },
  "Engin gögn á þessu tímabili.": { is: "Engin gögn á þessu tímabili.", en: "No data for this period." },
  "Áætlað vs raun-tímar": { is: "Áætlað vs raun-tímar", en: "Planned vs actual hours" },
  "Virkja": { is: "Virkja", en: "Activate" },
  "Óvirkja": { is: "Óvirkja", en: "Deactivate" },
  "Vista…": { is: "Vista…", en: "Saving…" },
  "Breyta vakt": { is: "Breyta vakt", en: "Edit shift" },
  "Í dag": { is: "Í dag", en: "Today" },
  "Þessi mánuður": { is: "Þessi mánuður", en: "This month" },
  "Búið til": { is: "Búið til", en: "Generated" },
  "janúar": { is: "janúar", en: "January" },
  "febrúar": { is: "febrúar", en: "February" },
  "mars": { is: "mars", en: "March" },
  "apríl": { is: "apríl", en: "April" },
  "maí": { is: "maí", en: "May" },
  "júlí": { is: "júlí", en: "July" },
  "ágúst": { is: "ágúst", en: "August" },
  "september": { is: "september", en: "September" },
  "október": { is: "október", en: "October" },
  "nóvember": { is: "nóvember", en: "November" },
  "desember": { is: "desember", en: "December" },
  "Ársfj.": { is: "Ársfj.", en: "Quarter" },
  "Tímar": { is: "Tímar", en: "Hours" },
  "Yfirvinna": { is: "Yfirvinna", en: "Overtime" },
  "vs maí": { is: "vs. maí", en: "vs. May" },
  "vs í gær": { is: "vs. í gær", en: "vs. yesterday" },
  "vs fyrri viku": { is: "vs. fyrri viku", en: "vs. previous week" },
  "Allar deildir": { is: "Allar deildir", en: "All departments" },
  "Allir staðir": { is: "Allar starfsstöðvar", en: "All locations" },
  "Leita að starfsmanni": { is: "Leita að starfsmanni…", en: "Search employees…" },

  // Dashboard
  "Sérsníða": { is: "Sérsníða", en: "Customize" },
  "Komdu þér af stað með VAKTO": { is: "Komdu rekstrinum af stað með VAKTO", en: "Onboard your business with VAKTO" },
  "3 af 5 skref kláruð — settu kerfið upp á nokkrum mínútum.": { is: "3 af 5 skrefum lokið — Grunnuppsetning tekur aðeins örfáar mínútur.", en: "3 of 5 onboarding steps completed — Fully set up within minutes." },
  "Fela": { is: "Fela", en: "Hide" },
  "Fyrirtæki & staðir": { is: "Fyrirtæki & staðir", en: "Company & locations" },
  "Bæta við starfsfólki": { is: "Bæta við starfsfólki", en: "Add personnel" },
  "Setja launataxta": { is: "Setja launataxta", en: "Set pay rates" },
  "Gera fyrsta vaktaplan": { is: "Gera fyrsta vaktaplan", en: "First schedule" },
  "Tengja launakerfi": { is: "Tengja launahugbúnað", en: "Link payroll platform" },
  "Í gær · 24. júní 2026": { is: "Í gær · 24. júní 2026", en: "Yesterday · 24 June 2026" },
  "Tímar og laun gærdagsins eru komin inn — dagurinn í dag uppfærist í rauntíma.": { is: "Tímaskráningar og reiknaður launakostnaður gærdagsins liggja fyrir. Dagurinn í dag uppfærist í rauntíma.", en: "Yesterday's structural hours and calculated pay are verified. Today's live operations refresh in real time." },
  "Áætlaðir tímar": { is: "Áætlaðir tímar", en: "Scheduled hours" },
  "Raun tímar": { is: "Unnir tímar (raun)", en: "Actual hours worked" },
  "Frávik": { is: "Tímafrávik", en: "Variance" },
  "Launakostnaður gærdagsins": { is: "Launakostnaður gærdagsins", en: "Yesterday's total labor cost" },
  "Laun% 32,4% · 47 vaktir · 8,2% yfirvinna": { is: "Launahlutfall 32,4% · 47 vaktir · 8,2% yfirvinna", en: "Labor ratio 32.4% · 47 shifts · 8.2% overtime burden" },
  "Laun af tekjum": { is: "Launahlutfall af tekjum", en: "Labor as % of revenue" },
  "Launakostnaður (vika)": { is: "Launakostnaður (vikutala)", en: "Weekly labor cost" },
  "Unnir tímar (vika)": { is: "Vinnustundir (vika)", en: "Weekly hours worked" },
  "/ 368 áætl": { is: "/ 368 áætlaðar", en: "/ 368 scheduled" },
  "yfir plani": { is: "fram úr áætlun", en: "above schedule" },
  "Yfirvinna (vika)": { is: "Yfirvinnutímar (vika)", en: "Weekly overtime hours" },
  "Launakostnaður — samanburður": { is: "Samanburður á launakostnaði", en: "Labor cost comparison" },
  "þetta tímabil vs fyrra": { is: "núverandi tímabil vs. fyrra", en: "current period vs. previous" },
  "Þetta tímabil": { is: "Þetta tímabil", en: "This period" },
  "Fyrra tímabil": { is: "Fyrra tímabil", en: "Previous period" },
  "Breyting": { is: "Frávik / breyting", en: "Net change" },
  "Vinnum við eftir plani?": { is: "Er farið eftir vaktaplani?", en: "Are operations meeting the schedule?" },
  "raun tímar vs áætlun · þessi vika": { is: "rauntímar á móti áætlun · þessi vika", en: "actual vs. planned hours · current week" },
  "94% eftir plani": { is: "94% fylgni við áætlun", en: "94% schedule adherence" },
  "Þarf athygli": { is: "Krefst athygli stjórnanda", en: "Needs attention" },
  "3 atriði": { is: "3 ábendingar", en: "3 alerts" },
  "Yfirvinnu-áhætta: Ómar": { is: "Yfirvinnuhætta: Ómar", en: "Overtime alert: Ómar" },
  "18 klst yfir starfshlutfalli í mánuðinum": { is: "Kominn 18 klst. fram úr starfshlutfalli í þessum mánuði", en: "Log represents 18 hours above contract quota this month" },
  "Hvíldartími: Jón": { is: "Lögboðinn hvíldartími: Jón", en: "Rest window breach: Jón" },
  "9 klst milli vakta — undir 11 klst lágmarki": { is: "aðeins 9 klst. á milli vakta — undir lögboðnu 11 klst. lágmarki", en: "9-hour window between shifts — fails the 11-hour legal minimum" },
  "laga": { is: "Laga", en: "Fix" },
  "Vantar útstimplun: Mína": { is: "Útstimplun vantar: Mína", en: "Missing clock-out: Mína" },
  "stimplaði inn 08:02, engin útstimplun í gær": { is: "innstimplun kl. 08:02, en engin útstimplun skráð í gær", en: "clocked in at 08:02, no departure timestamp recorded" },
  "skoða": { is: "Skoða", en: "Review" },
  "Mánuðurinn · júní 2026": { is: "Mánuðurinn · júní 2026", en: "Current Month · June 2026" },
  "· borið saman við maí": { is: "· Samanburður við maí", en: "· track variance against May" },
  "Unnir tímar": { is: "Heildarvinnustundir", en: "Total hours worked" },
  "Launakostn. (byrði)": { is: "Launagjöld (með launatengdum gjöldum)", en: "Labor burden (fully loaded)" },
  "Laun% (með byrði)": { is: "Launahlutfall (með launatengdum gjöldum)", en: "Labor% (including burden)" },
  "Launaspá (mánuður)": { is: "Launakostnaðarspá (mánuður)", en: "End-of-month pay forecast" },
  "brúttó · fyrir byrði": { is: "Heildarlaun · fyrir launatengd gjöld", en: "gross pay · before employer burden" },
  "batnar": { is: "Í jákvæðri þróun", en: "improving trend" },

  // Attendance
  "Sækja CSV": { is: "Flytja út (CSV)", en: "Export CSV" },
  "Á vakt núna": { is: "Mættir á vakt núna", en: "Active on shift now" },
  "Mætti of seint": { is: "Seinkomur", en: "Late arrivals" },
  "Vantar útstimplun": { is: "Útstimplun vantar", en: "Missing clock-outs" },
  "Frávik (klst)": { is: "Tímafrávik (klst)", en: "Variance (hrs)" },
  "Fer yfir áætlun": { is: "Fram úr áætlun", en: "Exceeding planned schedule" },
  "stefnir í yfirvinnu eða aukinn kostnað": { is: "áhætta á auknum yfirvinnukostnaði", en: "indicates trending toward overtime or budget inflation" },
  "Áætlað vs raun í dag": { is: "Áætlað vs. raun í dag", en: "Planned vs. actual tracking today" },
  "Áætlaður launakostnaður": { is: "Áætlaður launakostnaður", en: "Projected labor cost" },
  "Raun launakostnaður": { is: "Raunverulegur launakostnaður", en: "Actual labor cost accumulated" },
  "Raun laun% (klukknaðir tímar)": { is: "Raunverulegt launahlutfall (stimplaðir tímar)", en: "Actual labor% (clocked-hour analysis)" },
  "Samþykkja": { is: "Samþykkja", en: "Approve" },
  "Tímaskráning vikunnar": { is: "Tímaskráningar í þessari viku", en: "Time tracking entries this week" },
  "smelltu á röð til að skoða og samþykkja": { is: "veldu línu til að fara yfir og samþykkja færslu", en: "select an entry to review and validate" },
  "Samþykkja allt": { is: "Samþykkja allar tímaskráningar", en: "Approve all pending" },
  "3 bíða samþykkis": { is: "3 færslur bíða samþykkis", en: "3 entries awaiting validation" },
  "th:Starfsm.": { is: "Starfsmaður", en: "Employee" },
  "Áætluð vakt": { is: "Áætluð vakt", en: "Scheduled shift" },
  "Stimplað inn": { is: "Innstimplun", en: "Clocked in" },
  "Stimplað út": { is: "Útstimplun", en: "Clocked out" },
  "Áætl.": { is: "Áætl.", en: "Sched." },
  "Raun": { is: "Raun", en: "Actual" },
  "Staða": { is: "Staða", en: "Status" },
  "Samþykki": { is: "Samþykkt", en: "Approval status" },

  // Payroll
  "↗ Flytja í Payday": { is: "↗ Flytja í Payday", en: "↗ Export to Payday" },
  "Launatímabil · 21. maí – 20. júní 2026": { is: "Launatímabil · 21. maí – 20. júní 2026", en: "Payroll cycle · 21 May – 20 June 2026" },
  "Drög — bíður samþykkis": { is: "Launadrög — bíður samþykkis stjórnanda", en: "Payroll Draft — awaiting executive approval" },
  "Starfsmenn": { is: "Fjöldi starfsmanna", en: "Active personnel" },
  "Brúttó": { is: "Heildarlaun (Brúttó)", en: "Gross earnings" },
  "Forskoða": { is: "Forskoða", en: "Preview" },
  "Keyra launakeyrslu": { is: "Læsa og keyra laun", en: "Execute payroll run" },
  "Útborgað (júní)": { is: "Útgreidd laun (júní)", en: "Net payouts (June)" },
  "Heildarkostnaður": { is: "Heildarlaunagjöld fyrirtækis", en: "Total employment cost" },
  "byrði": { is: "launatengd gjöld", en: "employer burden" },
  "Staðgreiðsla": { is: "Staðgreiðsla skatta", en: "Withholding tax" },
  "Tryggingagjald": { is: "Tryggingagjald", en: "Insurance levy" },
  "Útborgað": { is: "Ráðstöfunarlaun (Útborgað)", en: "Net pay" },
  "Lífeyrir": { is: "Lífeyrissjóðir", en: "Pension funds" },
  "Orlof": { is: "Orlofsreikningur", en: "Holiday allowance" },
  "Launakeyrsla — sundurliðun per starfsmann": { is: "Launakeyrsla — Sundurliðun á starfsmenn", en: "Payroll Ledger — Detailed employee breakdown" },
  "21. maí – 20. júní 2026 · smelltu á starfsmann fyrir launaseðil": { is: "21. maí – 20. júní 2026 · Veldu starfsmann til að sjá nákvæman seðil", en: "21 May – 20 June 2026 · Select a team member to access individual payslip data" },
  "Allir seðlar": { is: "Sækja alla seðla", en: "All payroll documents" },
  "Starfsmaður": { is: "Starfsmaður", en: "Employee" },
  "Lífeyrir+félag": { is: "Lífeyrir & Stéttarfélag", en: "Pension & Union dues" },
  "Samtals · 12 starfsm.": { is: "Samtals · 12 starfsmenn", en: "Total · 12 active staff" },
  "Launakeyrslur — yfirlit": { is: "Launakeyrslur — Sögulegt yfirlit", en: "Payroll history — Overview" },
  "sundurliðun eftir mánuðum": { is: "mánaðarleg sundurliðun launa", en: "monthly accounting breakdown" },
  "Byrði — júní 2026": { is: "Launatengd gjöld (byrði) — Júní 2026", en: "Employer burden analysis — June 2026" },
  "Brúttólaun": { is: "Heildarlaun (Brúttólaun)", en: "Gross wages" },
  "Orlof 10,17%": { is: "Áunnið orlof 10,17%", en: "Holiday pay accrual 10.17%" },
  "Mótframlag lífeyris 11,5%": { is: "Mótframlag í lífeyrissjóð 11,5%", en: "Employer pension contribution 11.5%" },
  "Tryggingagjald 6,35%": { is: "Tryggingagjald atvinnurekenda 6,35%", en: "State insurance levy 6.35%" },
  "Útflutningur": { is: "Gagnaútflutningur", en: "Data transfer" },
  "launakeyrsla & skil — tilbúið": { is: "launavinnsla og skýrsluskil — tilbúið til sendingar", en: "payroll metrics & reporting — ready for submission" },
  "sundurliðun per starfsmann": { is: "sundurliðun á hvern starfsmann", en: "breakdown per employee line" },
  "Flytja": { is: "Flytja", en: "Export" },
  "Sækja": { is: "Sækja", en: "Download" },
  "Vakto reiknar — Payday sér um skil, greiðslur og opinbera skýrslugerð.": { is: "VAKTO sér um nákvæman útreikning — Payday annast rafræn skil, greiðslumiðlun og opinbera skýrslugerð.", en: "VAKTO processes structural mathematics — Payday executes institutional filings, bank transfers, and tax reports." },

  // Settings
  "Land & launareglur": { is: "Staðsetning & launareglur", en: "Jurisdiction & pay rules" },
  "Ísland (virkt)": { is: "Ísland (gildandi reglur)", en: "Iceland (active framework)" },
  "staðgreiðsla, tryggingagjald, lífeyrir, orlof": { is: "staðgreiðsla skatta, tryggingagjald, lífeyrissjóðir, lögboðið orlof", en: "withholding tax, insurance levy, pension mandates, accrued holiday allowance" },
  "virkt": { is: "í gildi", en: "active" },
  "virk": { is: "í gildi", en: "active" },
  "Fleiri lönd": { is: "Stuðningur við önnur lönd", en: "International regions" },
  "Noregur, Danmörk, Bretland": { is: "Noregur, Danmörk, Bretland", en: "Norway, Denmark, United Kingdom" },
  "væntanlegt": { is: "í þróun", en: "coming soon" },
  "Mótframlag lífeyris": { is: "Mótframlag í lífeyrissjóð", en: "Employer pension match" },
  "Launatímabil": { is: "Uppsetning launatímabila", en: "Payroll cycle parameters" },
  "Tengingar": { is: "Samþættingar (Integrations)", en: "System integrations" },
  "launakeyrsla & skil": { is: "launakeyrsla og opinber skil", en: "payroll automation & reporting" },
  "tengt": { is: "tengt", en: "Connected" },
  "velta í rauntíma — laun vs velta · smelltu til að sækja veltu": { is: "velta í rauntíma — samanburður á launum og veltu · smelltu til að samstilla", en: "real-time revenue — labor tracking vs. sales analytics · click to pull current sales data" },
  "POS / sölukerfi": { is: "POS / Sölukerfi", en: "POS / Sales systems" },
  "tengja": { is: "tengja", en: "Connect" },
  "Staðir": { is: "Starfsstöðvar", en: "Locations & Branches" },
  "+ Bæta við stað": { is: "+ Ný starfsstöð", en: "+ Add location" },
  "Hver staður hefur eigin starfsfólk, vaktaplan, laun% og tímabelti — fyrir keðjur og mörg útibú.": { is: "Sérhver starfsstöð heldur utan um eigið vaktaplan, starfsfólk, launahlutfall og tímabelti — tilvalið fyrir keðjurekstur.", en: "Each commercial unit operates with localized staff, distinct schedules, independent labor% targets, and designated time zones." },
  "nýtt": { is: "nýtt", en: "New" },
  "Stöður (positions)": { is: "Starfsheiti / Stöður", en: "Job roles & positions" },
  "+ Ný staða": { is: "+ Nýtt starfsheiti", en: "+ New role definition" },
  "Notendur & aðgangur": { is: "Notendastýring & réttindi", en: "User administration & permissions" },
  "+ Bjóða notanda": { is: "+ Bjóða nýjum notanda", en: "+ Invite user access" },
  "Eigandi — fullur aðgangur": { is: "Eigandi — full réttindi og kerfisstjórnun", en: "Owner — unrestricted administrative control" },
  "Eigandi": { is: "Aðaleigandi", en: "Primary Owner" },
  "Rekstrarstjóri — vaktir, laun, skýrslur": { is: "Rekstrarstjóri — umsýsla með vöktum, launum og skýrslum", en: "Operations manager — complete management of schedules, payroll, and logs" },
  "Stjórnandi": { is: "Vaktstjóri / Stjórnandi", en: "Manager access" },
  "eigin vaktir, tímar og laun": { is: "aðgangur takmarkast við eigin vaktir, tíma og launaloga", en: "access restricted to personal scheduling, logged hours, and digital payslips" },
  "Áskrift & greiðslur": { is: "Áskriftarstýring & reikningar", en: "Subscription & billing management" },
  "Vakto Business · mánaðarlega": { is: "VAKTO Business · Mánaðarleg áskrift", en: "VAKTO Business plan · Monthly billing cycle" },
  "Fjöldi notenda": { is: "Fjöldi notenda", en: "Active users" },
  "Verð á notanda": { is: "Verð á notanda", en: "Price per user" },
  "Samtals": { is: "Samtals", en: "Total" },
  "Næsta greiðsla": { is: "Næsta greiðsla", en: "Next payment" },
  "Greiðslumáti": { is: "Greiðslumáti", en: "Payment method" },
  "Uppfæra kort": { is: "Uppfæra kort", en: "Update card" },
  "Reikningar": { is: "Reikningar", en: "Invoices" },
  "Verð aðlagast sjálfkrafa þegar notendum fjölgar eða fækkar (per-notanda). Lítil teymi (≤5 starfsmenn) ókeypis.": { is: "Mánaðarlegt áskriftarverð uppfærist sjálfkrafa miðað við fjölda virkra starfsmanna. Lítil teymi (fimm eða færri) eru með frían aðgang.", en: "Subscription tiers dynamically update based on active seat volume. Free tiers apply to micro teams maintaining 5 or fewer members." },

  // Reports
  "Deild": { is: "Deild", en: "Department" },
  "Velta á starfsmann": { is: "Velta á hvern starfsmann", en: "Revenue generation per capita" },
  "Velta á launatíma": { is: "Velta per unna launastund", en: "Revenue yield per labor hour" },
  "Yfirvinna % af tímum": { is: "Hlutfall yfirvinnu af heildartímum", en: "Overtime volume ratio" },
  "Mætingahlutfall": { is: "Mætingarhlutfall teymis", en: "Staff attendance rate" },
  "Vaktaplan vs raun-tímar": { is: "Áætlað vaktaplan vs. raunvinnutímar", en: "Scheduled parameters vs. actual clock-ins" },
  "áætlað á móti klukknuðum tímum — þessi vika vs fyrri vika": { is: "áætlað skipulag á móti raunverulegum stimplunum — samanburður á vikum", en: "structural plan variables vs. verified clock logs — current vs. prior week analysis" },
  "Áætl. klst": { is: "Áætl. klst.", en: "Planned hrs" },
  "Raun klst": { is: "Raun klst.", en: "Actual hrs" },
  "Fyrri vika": { is: "Fyrri vika", en: "Prior week" },
  "Raun kostn.": { is: "Raun kostn.", en: "Actual cost" },
  "Tímabanki starfsfólks": { is: "Tímabanki starfsfólks", en: "Corporate staff time bank" },
  "uppsafnað +/− vs vinnuskylda": { is: "uppsafnað jafnvægi (+/−) á móti samningsbundinni vinnuskyldu", en: "accrued balance tracking (+/−) relative to contractual work obligation" },
  "Vinnuskylda": { is: "Vinnuskylda", en: "Required" },
  "Unnið": { is: "Unnið", en: "Worked" },
  "Staða banka": { is: "Staða banka", en: "Balance" },
  "Skýrslusafn": { is: "Skýrslusafn og útdrættir", en: "Report catalog" },
  "smelltu til að sækja — PDF eða Excel": { is: "smelltu til að hlaða niður skrá — á PDF eða Excel formi", en: "select an export preference to download — available in PDF or Excel formats" },

  // Performance
  "Júní 2026 vs maí 2026": { is: "Júní 2026 vs. maí 2026", en: "June 2026 vs. May 2026" },
  "Velta": { is: "Heildarvelta", en: "Gross revenue" },
  "Launakostnaður (byrði)": { is: "Launakostnaður (með launatengdum gjöldum)", en: "Total labor burden (fully loaded)" },
  "Framlegð": { is: "Framlegð rekstrar", en: "Operating margin" },
  "Velta vs spá": { is: "Raunveruleg velta vs. veltuspá", en: "Actual revenue vs. budget forecast" },
  "Unnið eftir áætlun": { is: "Fylgni við vaktaplan", en: "Schedule fidelity" },
  "Launakostnaður": { is: "Launakostnaður", en: "Labor expenditure" },
  "Launakostn.": { is: "Launakostn.", en: "Labor cost" },
  "Laun%": { is: "Launahlutfall %", en: "Labor cost %" },
  "Laun% vs maí": { is: "Launahlutfall vs. maí", en: "Labor% variance vs. May" },
  "Staður": { is: "Starfsstöð", en: "Business branch" },
  "Samanburður tímabila": { is: "Samanburður á milli tímabila", en: "Comparative period analysis" },
  "þetta tímabil · síðasta tímabil · sama tímabil í fyrra": { is: "núverandi tímabil · síðasta tímabil · sama tímabil á fyrra ári", en: "current framework window · immediate prior window · year-over-year match window" },
  "Mælikvarði": { is: "Árangursmælikvarði", en: "Performance metric" },
  "Júní 2026": { is: "Júní 2026", en: "June 2026" },
  "Maí 2026": { is: "Maí 2026", en: "May 2026" },
  "Júní 2025": { is: "Júní 2025", en: "June 2025" },
  "Breyting (mán)": { is: "Breyting á milli mánaða", en: "Month-over-month delta" },
  "vs í fyrra": { is: "vs. fyrra ár (YoY)", en: "vs. previous year" },
  "Velta vs launakostnaður": { is: "Samhengi veltu og launakostnaðar", en: "Revenue optimization vs. labor burden" },
  "6 mánuðir": { is: "Síðustu 6 mánuðir", en: "Rolling 6-month view" },
  "Laun% þróun vs 30% markmið": { is: "Þróun launahlutfalls vs. 30% rekstrarmarkmið", en: "Labor% vector tracking vs. 30% baseline efficiency target" },
  "síðustu 6 mánuðir": { is: "yfirlit yfir síðustu 6 mánuði", en: "rolling historical 6-month evaluation" },
  "Samanburður staða": { is: "Samanburður á milli starfsstöðva", en: "Cross-location efficiency comparison" },
  "hver staður — velta, laun% og framlegð, breyting milli mánaða": { is: "greining per starfsstöð — velta, launahlutfall, framlegð og mánaðarlegar sveiflur", en: "granular analysis per location — revenue generation, labor% ratios, profit margin metrics, and delta logs" },
  "Greining eftir deild": { is: "Greiningar og sundurliðun eftir deildum", en: "Departmental breakdown matrix" },
  "laun% per deild · júní": { is: "launahlutfall per deild · júní", en: "localized labor% calculations per department layer · June" },
  "Launasundurliðun": { is: "Launasundurliðun og kostnaðardreifing", en: "Capital allocation breakdown" },
  "hvert peningarnir fara": { is: "ítarleg greining á dreifingu fjármagns", en: "comprehensive mapping of operational currency distribution" },
  "perf:staff": { is: "Starfsfólk", en: "Direct personnel wages" },
  "Ríkið": { is: "Opinber gjöld (Ríkið)", en: "Government tax allocations" },
  "Sjóðir": { is: "Lífeyris- og stéttarfélagssjóðir", en: "Institutional & benefits funds" },
  "perf:ai1": { is: " er yfir áætluðu markmiði og sýnir neikvæða þróun á milli mánaða — drifkrafturinn er yfirvinna í eldhúsi. Ef Umi myndi ná sama launahlutfalli og Reykjavík Asian myndi það spara fyrirtækinu ", en: " is performing above target parameters and exhibiting a negative month-over-month trajectory, heavily driven by kitchen overtime. Aligning Umi with the structural labor efficiency of Reykjavík Asian would recover " },
  "perf:ai2": { is: " á hverjum einasta mánuði.", en: " in monthly cash flow equivalents." },

  // Employee self-service (Mitt svæði)
  "Yfirlit": { is: "Yfirlit yfir mitt svæði", en: "Dashboard overview" },
  "Mínar vaktir": { is: "Mínar vaktir framundan", en: "My schedule roster" },
  "Laun": { is: "Mín launamál", en: "My earnings feed" },
  "Réttindi": { is: "Mín réttindi & orlof", en: "My benefits & rights" },
  "Prófíll": { is: "Notendaprófíllinn minn", en: "My personal profile" },
  "emp:meta": { is: "Starfsmaður · Kaffi Krónan · Eldhússtörf", en: "Team Member · Kaffi Krónan · Kitchen Crew" },
  "Á vakt síðan 08:02": { is: "Á vakt, stimplað(ur) inn síðan 08:02", en: "Active on shift since 08:02" },
  "Ekki á vakt": { is: "Ekki skráð(ur) á vakt", en: "Off duty" },
  "Stimpla út": { is: "Stimpla mig út", en: "Clock out" },
  "Stimpla inn": { is: "Stimpla mig inn", en: "Clock in" },
  "Næsta vakt": { is: "Næsta vakt á dagskrá", en: "Next scheduled shift" },
  "Verkefni vaktarinnar": { is: "Verkefnalisti vaktarinnar", en: "Shift task requirements" },
  "Opna kassa & kveikja á græjum": { is: "Opna sjóðvél og ræsa tæki/búnað", en: "Initialize POS terminal & power on workstation hardware" },
  "Fylla á sósur og meðlæti": { is: "Fara yfir og fylla á hráefni/meðlæti", en: "Audit and restock condiment inventory stations" },
  "Þrífa grill fyrir lokun": { is: "Þrífa grill- og eldunarsvæði fyrir lokun", en: "Execute deep-clean checklist for kitchen hardware prior to close" },
  "Sækja um frí": { is: "Senda inn leyfisbeiðni", en: "Request time off" },
  "Skipta á vakt": { is: "Óska eftir vaktaskiptum", en: "Initiate shift swap" },
  "Opnar vaktir": { is: "Lausar og opnar vaktir", en: "Available open shifts" },
  "Skrá framboð": { is: "Uppfæra mitt framboð", en: "Update my availability" },
  "Mitt vaktaplan · 22.–28. júní": { is: "Mitt vaktaplan · 22.–28. júní", en: "My professional calendar · 22–28 June" },
  "Samantekt": { is: "Samantekt á vinnutíma", en: "Shift accumulation metrics" },
  "Tímar vikunnar": { is: "Heildartímar í þessari viku", en: "Hours completed this week" },
  "Tímar mánaðar (til þessa)": { is: "Heildartímar í mánuðinum (til þessa)", en: "Month-to-date total hours logged" },
  "Næsta útborgun": { is: "Áætluð næsta útborgun", en: "Estimated next payday" },
  "Laun — júní 2026 (áætlað)": { is: "Launaspá — Júní 2026 (Áætluð)", en: "Pay Projection — June 2026 (Estimated calculation)" },
  "Dagvinna": { is: "Klukknuð dagvinna", en: "Standard daytime hours" },
  "Álög (kvöld/helgi)": { is: "Áunnin vaktaálög (kvöld / helgar)", en: "Accrued shift premiums (evening/weekend)" },
  "Brúttó laun": { is: "Heildarlaun (Brúttóupphæð)", en: "Total gross earnings" },
  "Lífeyrir 4% + félag 1%": { is: "Lífeyrisgreiðsla 4% + Stéttarfélag 1%", en: "Pension fund allocation 4% + Union due deduction 1%" },
  "Persónuafsláttur": { is: "Nýttur persónuafsláttur", en: "Applied personal tax credit (Persónuafsláttur)" },
  "Áætlað útborgað": { is: "Áætluð ráðstöfunarlaun (Útborgað)", en: "Projected net payout" },
  "Fyrri mánuðir (útborgað)": { is: "Söguleg útgreidd laun (Útborgað)", en: "Historical net pay archives" },
  "Sækja launaseðil (PDF)": { is: "Sækja launaseðil á PDF formi", en: "Download formal payslip (PDF)" },
  "Áunnir dagar": { is: "Áunnir orlofsdagar", en: "Accrued vacation days" },
  "Nýttir í ár": { is: "Nýttir leyfisdagar á árinu", en: "Days redeemed calendar year to date" },
  "Orlofssjóður": { is: "Söfnun í orlofssjóð", en: "Holiday fund balance" },
  "Tímabanki": { is: "Staða í tímabanka", en: "Time bank ledger balance" },
  "Vinnuskylda (mán)": { is: "Mánaðarleg vinnuskylda samkvæmt samningi", en: "Monthly legal shift hours quota" },
  "Veikindi & réttindi": { is: "Veikindaréttur & áunnin réttindi", en: "Sick leave balance & legal protections" },
  "Veikindadagar nýttir": { is: "Skráðir nýttir veikindadagar", en: "Sick leaves registered" },
  "Starfshlutfall": { is: "Samningsbundið starfshlutfall", en: "Contract employment ratio" },
  "Hvíldartími (11 klst)": { is: "Lögboðin lágmarkshvíld (11 klst)", en: "Mandatory rest cycle adherence (11 hrs)" },
  "Í lagi": { is: "Í lagi", en: "Compliant" },
  "Kjarasamningur": { is: "Skráður kjarasamningur", en: "Governing union agreement" },
  "dagar": { is: "dagar", en: "days" },
  "Smelltu á myndina til að hlaða upp nýrri": { is: "Smelltu hér til þess að hlaða inn nýrri prófílmynd", en: "Click target field to upload an updated profile picture" },
  "Fullt nafn": { is: "Fullt nafn", en: "Full legal name" },
  "Kennitala": { is: "Kennitala", en: "National ID number (kennitala)" },
  "prof:position": { is: "Starfsheiti / Staða", en: "Assigned job role" },
  "Sími": { is: "Símanúmer", en: "Mobile phone number" },
  "Netfang": { is: "Netfang starfsmanns", en: "Primary email address" },
  "Bankareikningur (laun)": { is: "Ráðstöfunarreikningur (laun)", en: "Direct deposit bank account" },
  "Vista breytingar": { is: "Vista upplýsingar", en: "Save data changes" },
  "Frá": { is: "Frá og með", en: "Effective from" },
  "Til": { is: "Til og með", en: "Effective until" },
  "Tegund": { is: "Flokkur leyfis", en: "Leave categorization" },
  "Frí (ólaunað)": { is: "Launalaust leyfi", en: "Unpaid leave of absence" },
  "Veikindi": { is: "Veikindaleyfi", en: "Sick leave log" },
  "Senda beiðni": { is: "Senda inn beiðni", en: "Submit formal request" },
  "Hakaðu við dagana sem þú getur unnið:": { is: "Veldu þá daga sem þú ert tiltæk(ur) til vinnu:", en: "Indicate available calendar blocks for scheduling:" },
  "Vista framboð": { is: "Vista tiltækileika", en: "Save availability matrix" },
  "Vaktin þín": { is: "Vaktin þín", en: "Your assigned shift" },
  "Skipta við": { is: "Óska eftir skiptum við", en: "Propose trade with" },
  "Hætta við": { is: "Hætta við", en: "Cancel" },
  "Sækja um": { is: "Sækja um", en: "Apply" },
  "Mán": { is: "Mán", en: "Mon" }, "Þri": { is: "Þri", en: "Tue" }, "Mið": { is: "Mið", en: "Wed" },
  "Fim": { is: "Fim", en: "Thu" }, "Fös": { is: "Fös", en: "Fri" }, "Lau": { is: "Lau", en: "Sat" }, "Sun": { is: "Sun", en: "Sun" },
  "req:leave:done": { is: "Leyfisbeiðni hefur verið send í kerfið og bíður yfirferðar stjórnanda", en: "Formal leave request successfully submitted — awaiting manager review" },
  "req:avail:done": { is: "Tiltækileiki þinn hefur verið vistaður", en: "Availability matrix updated successfully" },
  "req:swap:done": { is: "Beiðni um vaktaskipti hefur verið send og bíður samþykkis", en: "Shift swap offer broadcasted successfully — pending mutual validation" },

  // Schedule (Vaktaplan)
  "Afrita viku": { is: "Afrita vaktaplan viku", en: "Duplicate weekly template" },
  "Birta plan": { is: "Gefa út vaktaplan", en: "Publish final schedule" },
  "Þessi vika": { is: "Yfirlit yfir þessa viku", en: "Active week parameters" },
  "Biðja AI": { is: "Gervigreind (AI) bestun", en: "Optimize with AI" },
  "Vakt": { is: "Vaktarlína", en: "Shift assignment" },
  "Vaktir í viku": { is: "Heildarvaktir í þessari viku", en: "Shifts structured this week" },
  "Stöðugildi (FTE)": { is: "Mönnun í stöðugildum (FTE)", en: "FTE resource count" },
  "Klst þann dag": { is: "Heildarstundir þann dag", en: "Total hours targeted that day" },
  "Bæta starfsmanni á plan": { is: "Bæta starfsmanni á plan", en: "Add employee to schedule" },
  "Vaktategundir": { is: "Skilgreindar vaktategundir", en: "Shift categories" },
  "Dragðu vaktir milli reita — kostnaður uppfærist strax.": { is: "Dragðu og slepptu vöktum á milli daga/starfsmanna — Launakostnaður reiknast samstundis.", en: "Drag and drop shift elements within the framework — Operational financial metrics update instantly." },
  "AI-vaktaplan": { is: "Snjallvaktaplan (AI)", en: "AI Schedule Optimization Engine" },
  "segðu markmið — Vakto endurraðar": { is: "Settu inn markmið rekstrar og VAKTO endurskipuleggur mönnunina sjálfkrafa", en: "Define operational metric goals — VAKTO reallocates structural scheduling layouts instantly" },
  "Tímar eftir dögum": { is: "Tímar eftir dögum", en: "Hours by day" },
  "áætlað í planinu · þessi vika": { is: "heildarstundir samkvæmt virku vaktaplani · þessi vika", en: "aggregate structural hours within the active template · current week analytics" },
  "Beiðnir & opnar vaktir": { is: "Starfsmannabeiðnir & lausar vaktir", en: "Staffing requests & unassigned shifts" },
  "frá starfsfólki — samþykktu eða úthlutaðu": { is: "beiðnir frá starfsfólki — Yfirfarið, úthlutið eða samþykkið", en: "incoming staff workflow requests — Assign, cross-validate, or approve allocations" },
  "Á vakt": { is: "Skráðir á vakt", en: "Staff on duty" },
  "Tímar dagsins": { is: "Heildarstundir dagsins", en: "Accumulated daily hours" },
  "Kostnaður dagsins": { is: "Áætlaður kostnaður dagsins", en: "Calculated daily financial burn" },
  "Mönnunarþörf": { is: "Mönnunarþörf og deildarþyngd", en: "Target staffing prerequisites" },
  "+ Bæta við vakt": { is: "+ Ný vakt", en: "+ Add shift slot" },
  "smelltu á vakt til að færa eða breyta": { is: "veldu vakt til þess að breyta tímasetningu eða færslu", en: "select a shift element to modify parameters or transfer allocation" },
  "Engar vaktir þennan dag.": { is: "Engar vaktir skráðar á þessum degi.", en: "No shifts mapped to this calendar day." },
  "smelltu á dag til að opna · á vakt til að breyta": { is: "veldu dag til að stækka sýn · veldu vakt til að breyta", en: "select a day block to open details · click active shift to modify attributes" },
  "Biðja AI um vaktaplan": { is: "Láta gervigreind smíða vaktaplan", en: "Initialize AI scheduling draft" },
  "Demo-tillaga — settu ANTHROPIC_API_KEY í .env.local fyrir alvöru AI-vaktaplan.": { is: "Prófunarumhverfi — Skráðu gildan ANTHROPIC_API_KEY í .env.local til þess að virkja fulla virkni AI-vaktaplansins.", en: "Simulation layout — Configure active ANTHROPIC_API_KEY within environment variables (.env.local) to deploy production AI scheduling features." },
  "Lækka launakostnað um 10%": { is: "Lækka áætlaðan launakostnað um 10%", en: "Reduce labor expenditure by 10%" },
  "haltu mönnun en lægri launum": { is: "viðhalda mönnunargæðum en lágmarka álagskostnað", en: "preserve baseline staffing coverage while minimizing premium overlap" },
  "Minnka yfirvinnu": { is: "Lágmarka yfirvinnu", en: "Reduce overtime burden" },
  "dreifa tímum, laga hvíld": { is: "endurdreifa vinnustundum og tryggja lögboðna hvíld", en: "reallocate hour clusters, fix legal rest-period buffers" },
  "Halda launum undir 30% af veltu": { is: "Takmarka launakostnað við 30% af veltu", en: "Target labor cost under 30% of sales" },
  "stilla mönnun að veltuspá": { is: "aðlaga mönnun og vaktavinnu að spáðri söluveltunni", en: "harmonize staffing volumes directly with localized revenue data forecasts" },
  "keyra": { is: "Keyra", en: "Run" },
  "Samþykkja & birta": { is: "Samþykkja & gefa út", en: "Validate & publish" },
  "Breyta beiðni": { is: "Breyta beiðnifærslu", en: "Edit request configuration" },
  "Búa til með AI": { is: "Reikna tillögu með AI", en: "Synthesize with AI engine" },
  "Tillaga AI": { is: "Tillaga gervigreindar (AI)", en: "AI Optimized Draft" },
  "Lýstu því sem þú vilt á venjulegri íslensku — VAKTO býr til vaktirnar og þú samþykkir.": { is: "Skrifaðu óskir þínar á einfaldri íslensku — VAKTO smíðar drög að vöktunum sem þú svo yfirferð og samþykkir.", en: "Provide optimization criteria in plain text — VAKTO generates compliant shifts automatically for your administrative approval." },
  "Hafna": { is: "Hafna", en: "Reject" },
  "Úthluta": { is: "Úthluta", en: "Assign" },
  "skráð": { is: "skráð", en: "logged" },
  "4 ný": { is: "4 ný", en: "4 new" },
  "Ný vakt": { is: "Stofna nýja vakt", en: "Create shift parameter" },
  "sched:aiph": { is: "t.d. Setja Ómar á 2-2-3 vaktir á milli 11:00 og 22:00 út allan maímánuð", en: "e.g., Map Ómar to repeating 2-2-3 shifts from 11:00 to 22:00 throughout May" },
  "sched:ailoading": { is: "Smíða vaktatillögu sem uppfyllir kröfur um hvíldartíma, lágmarkar yfirvinnu og verndar launahlutfallið…", en: "Synthesizing an optimal scheduling matrix tailored to legal rest buffers, overtime parameters, and targeted labor% metrics…" },
  "VAKTO hugsar…": { is: "VAKTO hugsar…", en: "VAKTO is thinking…" },
  "Bestun vaktaplans": { is: "Bestun vaktakerfisins", en: "Schedule Optimization Analysis" },
  "Settu Ómar á 2-2-3 vaktir 11:00–22:00 yfir allan maí": { is: "Settu Ómar á 2-2-3 vaktir 11:00–22:00 yfir allan maí", en: "Schedule Ómar on 2-2-3 shifts 11:00–22:00 throughout May" },
  "Lágmarkaðu yfirvinnu í þessari viku": { is: "Lágmarkaðu yfirvinnu í þessari viku", en: "Minimize overtime this week" },
  "Mannaðu helgina með 2 í eldhúsi og 2 á sal": { is: "Mannaðu helgina með 2 starfsmönnum í eldhúsi og 2 á sal", en: "Staff the weekend with 2 in the kitchen and 2 on the floor" },
  "Afritaðu þessa viku á næstu 4 vikur": { is: "Afritaðu þessa viku á næstu 4 vikur", en: "Copy this week to the next 4 weeks" },
  "Skilgreindu þínar eigin vaktategundir — heiti, tíma, álag og lit. Þær birtast í vaktaplaninu.": { is: "Skilgreindu sérsniðnar vaktategundir — heiti vaktar, tímasetningar, álagsprósentur og litakóða sem munu birtast á vaktaplaninu.", en: "Configure customized shift criteria parameters — edit tracking labels, hours, localized premium modifiers, and visual colors for the grid." },
  "+33% morgun/kvöld": { is: "+33% morgun-/kvöldálag", en: "+33% morning/evening premium" },
  "+45% helgi": { is: "+45% helgarálag", en: "+45% weekend premium" },
  "+90% yfirvinna": { is: "+90% yfirvinnuálag", en: "+90% overtime rate" },
  "Næturálag": { is: "Næturvaktaálag", en: "Night shift premium" },
  "Eyða": { is: "Eyða", en: "Delete" },
  "Búa til nýja vaktategund": { is: "Skilgreina nýja vaktategund", en: "Configure new shift profile" },
  "Heiti": { is: "Heiti flokks", en: "Category label" },
  "t.d. Næturvakt": { is: "t.d. Næturvakt", en: "e.g., Night shift" },
  "Upphaf": { is: "Upphaf vaktar", en: "Shift start time" },
  "Lok": { is: "Lok vaktar", en: "Shift end time" },
  "Álag": { is: "Álagsprósenta", en: "Premium modifier" },
  "Litur": { is: "Litakóði", en: "Visual color assignment" },
  "Bæta við": { is: "Bæta við", en: "Add" },
  "Loka": { is: "Loka", en: "Close" },
  "Veldu starfsmann til að bæta í vaktaplanið.": { is: "Veldu viðeigandi starfsmann til að bæta við vaktaplanið.", en: "Select an employee to allocate within the schedule matrix." },
  "+ bæta": { is: "+ bæta við", en: "+ assign" },
  "Vaktategund": { is: "Vaktategund", en: "Shift configuration type" },
  "Sérsniðin vakt": { is: "Sérsniðin sérvakt", en: "Custom variable shift" },
  "Veldu tilbúna vaktategund eða stilltu tíma sjálf/ur. Vantar tegund?": { is: "Veldu forskráða vaktategund eða stilltu vinnutímann handvirkt. Vantar nýjan flokk?", en: "Apply a predefined shift matrix profile or input custom time parameters manually. Need a new configuration?" },
  "Búa til vaktategund": { is: "Stofna vaktategund", en: "Configure new type" },
  "Staða / dagur": { is: "Hlutverk / Dagur", en: "Position mapping / Day" },
  "Kokkur": { is: "Kokkur", en: "Chef" },
  "Þjónn / Sal": { is: "Þjónn / Sal", en: "Server" },
  "Bílstjóri": { is: "Bílstjóri", en: "Driver" },
  "Þú getur fært vaktina á annan dag eða starfsmann hér — eða dregið hana til í vikusýn.": { is: "Þú getur breytt úthlutun vaktarinnar á nýjan dag eða starfsmann hér — eða dregið hana til í aðal vikusýninni.", en: "Modify shift distribution parameters to a different date or staff member here — or drag dynamically across the week view interface." },
  "Vista": { is: "Vista", en: "Save" },
  "Afrita": { is: "Afrita", en: "Copy" },
  "Fjarlægja af plani": { is: "Eyða af vaktaplani", en: "Remove allocation from grid" },
  "sh:Dagvakt": { is: "Dagvakt", en: "Day" },
  "sh:Morgun": { is: "Morgunvakt", en: "Morning" },
  "sh:Mið": { is: "Miðvakt", en: "Mid" },
  "sh:Kvöld": { is: "Kvöldvakt", en: "Evening" },
  "Frí": { is: "Frí", en: "Off duty" },
  "frí": { is: "frí", en: "off" },
  "Sal": { is: "Salur", en: "Floor" },
  "Eldhús": { is: "Eldhús", en: "Kitchen" },
  "Stjórnun": { is: "Stjórnun", en: "Management" },
  "Dagvakt": { is: "Dagvakt", en: "Day shift" },
  "Morgunvakt": { is: "Morgunvakt", en: "Morning shift" },
  "Kvöldvakt": { is: "Kvöldvakt", en: "Evening shift" },
  "Helgarvakt": { is: "Helgarvakt", en: "Weekend shift" },
  "+33% fyrir 07:00": { is: "+33% álag fyrir 07:00", en: "+33% early morning premium (before 07:00)" },
  "+33% álag": { is: "+33% álag", en: "+33% shift premium" },
  "+45% helgarálag": { is: "+45% helgarálag", en: "+45% weekend premium" },
  "Líma-hamur:": { is: "Fjölfaldar-hamur (Líma):", en: "Paste duplication mode:" },
  "smelltu á reiti til að líma": { is: "veldu viðeigandi reiti til að líma vakt", en: "click specific cell blocks to copy-paste parameters" },
  "Hætta": { is: "Hætta", en: "Cancel" },
  "á vakt": { is: "á vakt", en: "on duty" },
  "vaktir": { is: "vaktir", en: "shifts" },
  "Mánudagur": { is: "Mánudagur", en: "Monday" },
  "Þriðjudagur": { is: "Þriðjudagur", en: "Tuesday" },
  "Miðvikudagur": { is: "Miðvikudagur", en: "Wednesday" },
  "Fimmtudagur": { is: "Fimmtudagur", en: "Thursday" },
  "Föstudagur": { is: "Föstudagur", en: "Friday" },
  "Laugardagur": { is: "Laugardagur", en: "Saturday" },
  "Sunnudagur": { is: "Sunnudagur", en: "Sunday" },
  "júní": { is: "júní", en: "June" },
  "Þriðjudagur er þyngstur (62 klst) en laugardagur undirmannaður um hádegi — færðu eina vakt af þriðjudegi á laugardag.": { is: "Þriðjudagur er með hæsta klukkustundafjöldann (62 klst.) en laugardagur sýnir undirmönnun um hádegi — Tillaga: Færðu eina vakt yfir á laugardag.", en: "Tuesday contains the highest volume load (62 hrs) while Saturday indicates structural understaffing at midday — optimization tip: move one shift allocation." },
  "Frí-beiðni: Bach": { is: "Orlofsbeiðni: Bach", en: "Time-off request: Bach" },
  "27.–28. júní · orlof": { is: "27.–28. júní · skráð orlof", en: "27–28 June · vacation accrual leave" },
  "Vaktaskipti: Mína ↔ Phong": { is: "Vaktaskipti: Mína ↔ Phong", en: "Shift swap agreement: Mína ↔ Phong" },
  "laugardagur 12–20 — báðir samþykktu": { is: "laugardagur kl. 12–20 — Báðir starfsmenn hafa samþykkt", en: "Saturday schedule block 12–20 — Validated by both parties" },
  "Opin vakt: laugardag 12–20": { is: "Opin laus vakt: Laugardagur 12–20", en: "Open shift slot: Saturday 12–20" },
  "2 starfsmenn sóttu um — Ha Vu, Dalya": { is: "2 starfsmenn hafa sótt um vaktina — Ha Vu, Dalya", en: "2 internal applications pending — Ha Vu, Dalya" },
  "Óframboð: Ómar": { is: "Óframboð skráð: Ómar", en: "Unavailability log: Ómar" },
  "getur ekki unnið fimmtudaga í júlí": { is: "óvinnufær á fimmtudögum í júlímánuði", en: "flagged unavailable on Thursdays throughout July" },
  "Heild:": { is: "Heildarsumma:", en: "Total tracking:" },
  "velta": { is: "rekstrarvelta", en: "gross revenue" },
  "laun": { is: "launakostnaður", en: "labor costs" },
  "fleiri": { is: "fleiri", en: "more" },
  "opnar": { is: "opnar", en: "open" },
  "ný": { is: "nýjar", en: "new" },
  "starfsm.": { is: "starfsm.", en: "staff" },
  "starfsmenn": { is: "starfsmenn", en: "personnel" },
  "grunntaxti": { is: "grunntaxti kjarasamnings", en: "baseline hourly rate" },
  "Tímar mánaðar": { is: "Heildarstundir í mánuði", en: "Accumulated hours this month" },
  "Vaktir í dag": { is: "Vaktatala í dag", en: "Shifts structured today" },
  "Vaktir í mánuði": { is: "Samtals vaktir í mánuði", en: "Total shifts this monthly cycle" },
  "vs": { is: "á móti", en: "vs." },
  "vs fyrri": { is: "vs. fyrra tímabil", en: "vs. prior period" },
  "Vika 26 vs vika 25": { is: "Vika 26 vs. vika 25", en: "Week 26 vs. Week 25" },
  "2. ársfj. vs 1. ársfj.": { is: "Ársfjórðungur 2 (Q2) vs. Ársfjórðungur 1 (Q1)", en: "Q2 metrics vs. Q1 performance window" },
  "2026 vs 2025": { is: "Rekstrarár 2026 vs. 2025", en: "Fiscal year 2026 vs. 2025 data" },
  "Skrá veltu handvirkt": { is: "Skrá veltutölur handvirkt", en: "Manual revenue data input" },
  "án Inventra — sláðu inn veltu til að sjá laun vs velta": { is: "án sjálfvirkrar Inventra samþættingar — Sláðu inn daglega veltu til að reikna út launahlutfall", en: "standalone mode without active Inventra link — Manually register sales trends to generate labor% profiles" },
  "slá inn": { is: "slá inn", en: "Enter" },
  "Skrá veltu": { is: "Veltuskráning", en: "Log sales data" },
  "Bæta við stað": { is: "Bæta við starfsstöð", en: "Register branch location" },
  "Ný staða": { is: "Stofna nýja stöðu", en: "Define job position" },
  "Bjóða notanda": { is: "Bjóða notanda", en: "Invite team member seat" },
  "Heiti staðar": { is: "Heiti starfsstöðvar", en: "Location naming profile" },
  "Heiti stöðu": { is: "Titill starfsheitis", en: "Position designation title" },
  "Grunntaxti (kr/klst)": { is: "Grunntaxti (kr./klst.)", en: "Base hourly wage (ISK/hr)" },
  "Hlutverk (aðgangur)": { is: "Aðgangshlutverk og réttindi", en: "System access role profile" },
  "Velta (kr)": { is: "Velta (kr.)", en: "Gross sales (ISK)" },
  "Dagsetning": { is: "Dagsetning skráningar", en: "Calendar date" },
  "Sláðu inn veltu dagsins (eða tímabils) til að reikna laun% án Inventra.": { is: "Skráðu inn veltu dagsins (eða ákveðins tímabils) til að reikna út launahlutfallið handvirkt án sölukerfistengingar.", en: "Input daily or dynamic batch revenue figures directly to track real-time labor cost analytics without a primary POS pipeline integration." },
  "Verktaki": { is: "Sjálfstætt starfandi / Verktaki", en: "Independent Contractor" },
  "Vaktstjóri": { is: "Vaktstjóri / Stjórnandi vaktar", en: "Shift Supervisor" },

  // Chat screen
  "chat:channel": { is: "Almennar tilkynningar — Allir", en: "Broadcast Announcements — General" },
  "chat:channelFull": { is: "Tilkynningarás — Allt starfsfólk", en: "Official Channel — All corporate personnel" },
  "chat:send": { is: "Senda skilaboð", en: "Broadcast message" },
  "chat:now": { is: "núna", en: "just now" },

  // Settings audit
  "audit:title": { is: "Kerfisaðgerðaskrá (Audit Log)", en: "System Audit Log Ledger" },
  "audit:sub": { is: "nýlegar breytingar og breytingasaga í kerfinu", en: "recent security, configuration and system access changes" },
  "audit:empty": { is: "Engar aðgerðir skráðar í aðgerðaskrá enn.", en: "No administrative entries logged in audit trail yet." },
};

const Ctx = createContext<{ lang: Lang; setLang: (l: Lang) => void }>({ lang: "is", setLang: () => {} });

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>("is");
  useEffect(() => {
    // Default is "is" (matches SSR); only switch if the saved choice differs.
    if (localStorage.getItem("vakto-lang") === "en") {
      const id = requestAnimationFrame(() => setLangState("en"));
      return () => cancelAnimationFrame(id);
    }
  }, []);
  function setLang(l: Lang) {
    setLangState(l);
    try { localStorage.setItem("vakto-lang", l); } catch {}
  }
  return <Ctx.Provider value={{ lang, setLang }}>{children}</Ctx.Provider>;
}

export function useLang() {
  const { lang, setLang } = useContext(Ctx);
  const t = (key: string) => DICT[key]?.[lang] ?? key;
  return { lang, setLang, t };
}
