// Allur texti forsíðunnar á íslensku og ensku. Skjámyndirnar sjálfar eru úr íslenska viðmótinu.
import type { SiteLang } from "./lang";

const is = {
  skip: "Fara beint í efni",
  h1a: "Vaktin, launin og yfirsýnin.", h1b: "Á einum stað.",
  lede: "Vaktaplan, stimpilklukka, launakeyrsla og ráðningarsamningar. Og launakostnaður sem hlutfall af veltu, í rauntíma.",
  try: "Prófa frítt", see: "Sjá kerfið",
  heroAlt: "Mælaborð VAKTO: laun sem hlutfall af veltu, unnir tímar og frávik",
  cap1b: "Laun sem % af veltu.", cap1: " Ein tala sem segir hvort vaktin borgar sig.",
  cap2b: "Grænt, gult eða rautt.", cap2: " Reiknað úr stimplunum jafnóðum, ekki í lok mánaðar.",
  featH: "Allt sem vaktin þarf.",
  dragAlt: "Vaktaplan vikunnar: vakt dregin á milli starfsmanna",
  t1h: "Vaktaplan á korteri.", t1p: "Dragðu vaktir til, afritaðu síðustu viku eða biddu gervigreindina um plan sem passar veltuspánni. Launakostnaðurinn reiknast á meðan.",
  t2h: "Stimplað í símanum.", t2p: "Eða á spjaldtölvu við innganginn. Staðsetning staðfest ef þú vilt.", t2alt: "VAKTO-appið: á vakt síðan 05:38, stimpla út",
  t3h: "Frávik með krónutölu.", t3p: "Hver mætti seint, hver fór fyrr og hvað það kostaði.", t3alt: "Tímaskráning með frávikum",
  t4h: "Laun eftir kjarasamningi.", t4p: "Álag, yfirvinna og uppbót reiknuð. Beint í Payday eða DK.", t4alt: "Launakeyrsla mánaðarins",
  t5h: "Spjaldtölva við innganginn.", t5p: "Starfsfólk ýtir á nafnið sitt eða skannar skírteinið í símanum. Enginn PIN-kóði að gleyma og enginn stimplar fyrir annan.", t5alt: "Stimpilklukkan á spjaldtölvu: allt starfsfólk og hver er á vakt",
  t6h: "Spjall fyrir hópinn.", t6p: "Rásir per deild og stað. Enginn Messenger-hópur með fyrrverandi starfsfólki.", t6alt: "Spjallrásir í VAKTO-appinu",
  darkH: "Fallegt í birtu. Líka á næturvaktinni.", darkP: "Kerfið fylgir stillingu tækisins. Dragðu til að bera saman.",
  cmpAria: "Bera saman ljóst og dökkt", cmpLight: "Vaktaplan í ljósu þema", cmpDark: "Vaktaplan í dökku þema",
  appAlt: "Appið í dökku þema: á vakt", appH: "Starfsfólkið fær appið.",
  appP: "Vaktirnar, stimplun, áætluð laun, orlofsstaða, frí og vaktaskipti. Og spjall og fréttaveita fyrir allan hópinn.",
  appTicks: ["iPhone og Android", "Íslenska, enska og víetnamska", "Tilkynning þegar planið breytist"],
  feedAlt: "Fréttaveita í appinu",
  showH: "Kynntu þér VAKTO.", showRole: "glærusýning", slideRole: "glæra", of: "af", slideN: "Glæra", pause: "Gera hlé", play: "Spila",
  slides: [
    { t: "VAKTO AI.", d: "Skrifaðu hvað vikan þarf á venjulegri íslensku. VAKTO AI semur drög að vaktaplani sem þú ferð yfir og samþykkir, og les kjarasamninginn fyrir þig með tilvísun í hverja grein.", alt: "Tillaga VAKTO AI: Moon færður á kvöldvakt á laugardag, launakostnaður óbreyttur 27,4%" },
    { t: "Vaktirnar í vasanum.", d: "Starfsfólk sér planið sitt, sækir um lausar vaktir og býður vaktir í skiptum. Spjallið er á sama stað.", alt: "Vaktir vikunnar í appinu", alt2: "Spjallrásir í appinu" },
    { t: "Fréttaveita fyrir vinnustaðinn.", d: "Nýr matseðill, breyttur opnunartími, mynd úr eldhúsinu. Festu það mikilvæga efst svo það týnist ekki.", alt: "Fréttaveitan í appinu" },
    { t: "Launaseðill sem stenst.", d: "Dagvinna, álag og yfirvinna sundurliðuð. Líka þegar mánuðurinn var 0 tímar og starfsmaðurinn þarf staðfestingu.", alt: "Launaseðill úr VAKTO" },
  ],
  conH: "Samningur á mínútu, undirritaður á annarri.",
  conP: "VAKTO fyllir út ráðningarsamning úr gögnum starfsmannsins, eftir formi Vinnumálastofnunar. Báðir skrifa undir í símanum og fá undirritað eintak í pósti.",
  conTicks: ["Fylgir formi Vinnumálastofnunar, á íslensku og ensku", "Undirritun með kóða í pósti eða rafrænum skilríkjum", "Fingrafar skjals og undirritunarskrá fylgja", "Launaseðlar og tímaskrár í sama stíl"],
  conAlt: "Fyrsta síða ráðningarsamnings: Kaffi Krónan ræður Ha Vu til starfa", stamp: "Undirritað rafrænt",
  passLbl: "STARFSMAÐUR", passRole: "STAÐA", passRoleV: "Þjónn", passKt: "KENNITALA", passNo: "NR.", passFoot: "VAKTO-4132-KK · skannaðu á stimpilklukku",
  walH: "Starfsmannaskírteinið er í símanum.",
  walP: "Í Apple og Google Wallet, með mynd, stöðu og QR-kóða. Kóðinn stimplar inn á spjaldtölvunni við innganginn, svo enginn þarf að muna PIN-kóða.",
  priceH: "Eitt verð. Allt innifalið.", amt: "9.990 kr", per: "/mán",
  price1: "5 virkir starfsmenn innifaldir.", price2: "1.490 kr á hvern virkan starfsmann umfram.",
  fine: "Án VSK. Þú borgar aðeins fyrir þá sem unnu í mánuðinum. 15% afsláttur ef greitt er árlega. 14 daga frí prufa, engin binding.",
};

const en: typeof is = {
  skip: "Skip to content",
  h1a: "Shifts, pay and the big picture.", h1b: "In one place.",
  lede: "Scheduling, time clock, payroll and employment contracts. Plus labor cost as a share of revenue, in real time.",
  try: "Try free", see: "See the product",
  heroAlt: "VAKTO dashboard: labor as a share of revenue, hours worked and deviations",
  cap1b: "Labor as % of revenue.", cap1: " One number that tells you whether the shift pays off.",
  cap2b: "Green, yellow or red.", cap2: " Calculated from clock-ins as they happen, not at month end.",
  featH: "Everything a shift needs.",
  dragAlt: "Weekly schedule: a shift dragged from one employee to another",
  t1h: "A schedule in fifteen minutes.", t1p: "Drag shifts around, copy last week or ask the AI for a plan that fits the revenue forecast. Labor cost updates as you go.",
  t2h: "Clock in on the phone.", t2p: "Or on a tablet by the entrance. Location verified if you want.", t2alt: "The VAKTO app: on shift since 05:38, clock out",
  t3h: "Deviations in krónur.", t3p: "Who came in late, who left early and what it cost.", t3alt: "Time tracking with deviations",
  t4h: "Pay by the union agreement.", t4p: "Premiums, overtime and bonuses calculated. Straight to Payday or DK.", t4alt: "This month's payroll",
  t5h: "A tablet at the entrance.", t5p: "Staff tap their name or scan the ID card on their phone. No PIN to forget, and nobody clocks in for someone else.", t5alt: "The time clock on a tablet: all staff and who is on shift",
  t6h: "Chat for the whole team.", t6p: "Channels per department and location. No Messenger group with former staff in it.", t6alt: "Chat channels in the VAKTO app",
  darkH: "Beautiful in daylight. And on the night shift.", darkP: "VAKTO follows your device setting. Drag to compare.",
  cmpAria: "Compare light and dark", cmpLight: "Schedule in light mode", cmpDark: "Schedule in dark mode",
  appAlt: "The app in dark mode: on shift", appH: "Your staff get the app.",
  appP: "Their shifts, clock-in, estimated pay, holiday balance, time off and shift swaps. Plus chat and a news feed for the whole team.",
  appTicks: ["iPhone and Android", "Icelandic, English and Vietnamese", "A notification when the schedule changes"],
  feedAlt: "News feed in the app",
  showH: "Get to know VAKTO.", showRole: "slideshow", slideRole: "slide", of: "of", slideN: "Slide", pause: "Pause", play: "Play",
  slides: [
    { t: "VAKTO AI.", d: "Describe what the week needs in plain language. VAKTO AI drafts a schedule for you to review and approve, and reads the union agreement for you with a reference to every clause.", alt: "VAKTO AI suggestion: Moon moved to Saturday's evening shift, labor cost unchanged at 27.4%" },
    { t: "Shifts in your pocket.", d: "Staff see their schedule, apply for open shifts and offer shifts to swap. The chat is right there too.", alt: "This week's shifts in the app", alt2: "Chat channels in the app" },
    { t: "A news feed for the workplace.", d: "A new menu, changed opening hours, a photo from the kitchen. Pin what matters so it doesn't get lost.", alt: "The news feed in the app" },
    { t: "A payslip that holds up.", d: "Day rate, premiums and overtime itemised. Even when the month was zero hours and the employee needs proof.", alt: "Payslip from VAKTO" },
  ],
  conH: "A contract in a minute, signed in the next.",
  conP: "VAKTO fills out the employment contract from the employee's details, following the Directorate of Labour's form. Both parties sign on their phone and get a signed copy by email.",
  conTicks: ["Follows the Directorate of Labour's form, in Icelandic and English", "Signed with an emailed code or electronic ID", "Document fingerprint and signing log included", "Payslips and timesheets in the same style"],
  conAlt: "First page of an employment contract: Kaffi Krónan hires Ha Vu", stamp: "Signed electronically",
  passLbl: "EMPLOYEE", passRole: "ROLE", passRoleV: "Server", passKt: "ID NUMBER", passNo: "NO.", passFoot: "VAKTO-4132-KK · scan at the time clock",
  walH: "The employee ID card lives on the phone.",
  walP: "In Apple and Google Wallet, with photo, role and QR code. The code clocks in on the tablet by the entrance, so nobody has to remember a PIN.",
  priceH: "One price. Everything included.", amt: "ISK 9,990", per: "/mo",
  price1: "5 active employees included.", price2: "ISK 1,490 per additional active employee.",
  fine: "Excl. VAT. You only pay for those who worked that month. 15% off when paid annually. 14-day free trial, no commitment.",
};

export const HOME_TEXT: Record<SiteLang, typeof is> = { is, en };
